<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jennifer HY Lin">
<meta name="dcterms.date" content="2022-08-02">

<title>Portfolio - Phenotypes associated with rare diseases</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Portfolio</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">Jennifer HY Lin</a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/jhylin"><i class="bi bi-github" role="img">
</i> 
 </a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/jenhylin"><i class="bi bi-twitter" role="img">
</i> 
 </a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Phenotypes associated with rare diseases</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Data analytics projects</div>
                <div class="quarto-category">R</div>
                <div class="quarto-category">Python</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Jennifer HY Lin </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">August 2, 2022</p>
      </div>
    </div>
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="initial-data-wrangling" class="level5">
<h5 class="anchored" data-anchor-id="initial-data-wrangling"><strong>Initial data wrangling</strong></h5>
<p>This dataset was also derived and downloaded from Orphanet, as another part in the “rare diseases” series. It contained 37 columns with 112,243 rows originally, which took quite a long time to load on RStudio (or could be due to my laptop capacity…). It loaded relatively faster on Jupyter notebook from Anaconda, so I then decided to clean it up first using Python<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> there. Some columns were removed which reduced the total number of columns from 37 to 13, while not changing any of the rows at all. The columns were also renamed to make it easier to read.</p>
</section>
<section id="source-of-dataset" class="level5">
<h5 class="anchored" data-anchor-id="source-of-dataset"><strong>Source of dataset</strong></h5>
<p>Orphadata: Free access data from Orphanet. © INSERM 1999. Available on <a href="http://www.orphadata.org/cgi-bin/index.php">http://www.orphadata.org</a>. Data version (XML data version). Dataset (.xml file) from http://www.orphadata.org/cgi-bin/epidemio.html. Latest date of update for the dataset: 14/6/2022 (last accessed 24/7/2022). Creative Commons Attribution 4.0 International.</p>
<p><img src="Genes.jpg" class="img-fluid"></p>
<p><em>Photo by</em> <a href="https://unsplash.com/@sangharsh_l?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Sangharsh Lohakare</a> on <a href="https://unsplash.com/s/photos/genes?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></p>
<p>The following libraries were used for the exploratory data analysis:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Read imported .csv file after data cleaning in Python.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"rare_disease_phenotypes.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 112243 Columns: 13
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (10): Disorder group, Disorder type, Diagnostic criteria, HPO frequency...
dbl   (2): HPO disorder &amp; clinical entity association count, Disorder Orphacode
dttm  (1): Validation date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<p>Note: HPO = human phenotype ontology</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">spec</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>cols(
  `Disorder group` = col_character(),
  `Disorder type` = col_character(),
  `HPO disorder &amp; clinical entity association count` = col_double(),
  `Diagnostic criteria` = col_character(),
  `HPO frequency` = col_character(),
  `HPO ID` = col_character(),
  `Preferred HPO term` = col_character(),
  `Disorder name` = col_character(),
  `Disorder Orphacode` = col_double(),
  Online = col_character(),
  Source = col_character(),
  `Validation date` = col_datetime(format = ""),
  `Validation status` = col_character()
)</code></pre>
</div>
</div>
</section>
<section id="exploratory-data-analysis" class="level5">
<h5 class="anchored" data-anchor-id="exploratory-data-analysis"><strong>Exploratory data analysis</strong></h5>
<p>Since I wasn’t intending for this project<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> to be extremely long (as most people would likely lose interests by then), I’d like to first ask a question about the dataset, in order to keep it at a reasonably short but informative length. So, here’s the question: what are the most common rare disorders and their associated phenotypic features?</p>
<p>To answer it, let’s observe the spread of the disorder groups and types first by formulating a contingency table.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>df_type <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="st">`</span><span class="at">Disorder group</span><span class="st">`</span>,<span class="st">`</span><span class="at">Disorder type</span><span class="st">`</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Number =</span> <span class="fu">n</span>())</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>df_type</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 3
# Groups:   Disorder group [3]
   `Disorder group`    `Disorder type`                                    Number
   &lt;chr&gt;               &lt;chr&gt;                                               &lt;int&gt;
 1 Disorder            Biological anomaly                                     41
 2 Disorder            Clinical syndrome                                     661
 3 Disorder            Disease                                             57920
 4 Disorder            Malformation syndrome                               37634
 5 Disorder            Morphological anomaly                                2644
 6 Disorder            Particular clinical situation in a disease or syn…    418
 7 Group of disorders  Category                                              479
 8 Group of disorders  Clinical group                                        952
 9 Subtype of disorder Clinical subtype                                     7394
10 Subtype of disorder Etiological subtype                                  4060
11 Subtype of disorder Histopathological subtype                              40</code></pre>
</div>
</div>
<p>After a quick view on the column of “Disorder group”, it mainly provided different disorder types a group label for each, which to a certain extent, was not necessary at this early stage. So this column was removed for now from the contingency table, in order to focus solely on, “Disorder type” with the number of counts (or times it appeared in the dataset).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>df_type <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="st">`</span><span class="at">Disorder type</span><span class="st">`</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Number =</span> <span class="fu">n</span>())</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>df_type</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 2
   `Disorder type`                                        Number
   &lt;chr&gt;                                                   &lt;int&gt;
 1 Biological anomaly                                         41
 2 Category                                                  479
 3 Clinical group                                            952
 4 Clinical subtype                                         7394
 5 Clinical syndrome                                         661
 6 Disease                                                 57920
 7 Etiological subtype                                      4060
 8 Histopathological subtype                                  40
 9 Malformation syndrome                                   37634
10 Morphological anomaly                                    2644
11 Particular clinical situation in a disease or syndrome    418</code></pre>
</div>
</div>
<p>Then to visualise this in a graphic way, a lollypop chart was built horizontally, with different types of rare disorders on the y-axis and the number of each type on the x-axis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> df_type, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Disorder type</span><span class="st">`</span>, <span class="at">y =</span> <span class="st">`</span><span class="at">Number</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Disorder type</span><span class="st">`</span>, <span class="at">xend =</span> <span class="st">`</span><span class="at">Disorder type</span><span class="st">`</span>, <span class="at">y =</span> <span class="dv">0</span>, <span class="at">yend =</span> <span class="st">`</span><span class="at">Number</span><span class="st">`</span>), <span class="at">colour =</span> <span class="st">"dark blue"</span>) <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">colour =</span> <span class="st">"dark green"</span>, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="PhenotypesRareDiseases_files/figure-html/lollypop%20chart-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Two disorder types stood out the most, with “Disease” type appeared 57,920 times and “Malformation syndrome” at 37,634 times. To understand further what each of these two disorder types were, a direct reference<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> was used. According to the source of the dataset:</p>
<p>The definition of “Disease” in the rare disorder context was “a disorder with homogeneous therapeutic possibilities and an identified physiopathological mechanism…”, one thing also worth noting was that this type did not include any developmental anomalies.</p>
<p>For “Malformation syndrome”, this was defined as, “A disorder resulting from a developmental anomaly involving more than one morphogenetic field. Malformative sequences and associations are included.”</p>
<p>To demonstrate this in a tabular form, with corresponding proportions of each disorder type in the dataset, the following codes were used:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="st">`</span><span class="at">Disorder type</span><span class="st">`</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop =</span> n<span class="sc">/</span><span class="fu">sum</span>(n))</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>df1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 3
   `Disorder type`                                            n     prop
   &lt;chr&gt;                                                  &lt;int&gt;    &lt;dbl&gt;
 1 Biological anomaly                                        41 0.000365
 2 Category                                                 479 0.00427 
 3 Clinical group                                           952 0.00848 
 4 Clinical subtype                                        7394 0.0659  
 5 Clinical syndrome                                        661 0.00589 
 6 Disease                                                57920 0.516   
 7 Etiological subtype                                     4060 0.0362  
 8 Histopathological subtype                                 40 0.000356
 9 Malformation syndrome                                  37634 0.335   
10 Morphological anomaly                                   2644 0.0236  
11 Particular clinical situation in a disease or syndrome   418 0.00372 </code></pre>
</div>
</div>
<p>The table was then rearranged with proportions in descending order (from highest to lowest). It also showed the top two were “Disease” (51.6%) and “Malformation syndrome” (33.5%).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>df1 <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(prop))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 3
   `Disorder type`                                            n     prop
   &lt;chr&gt;                                                  &lt;int&gt;    &lt;dbl&gt;
 1 Disease                                                57920 0.516   
 2 Malformation syndrome                                  37634 0.335   
 3 Clinical subtype                                        7394 0.0659  
 4 Etiological subtype                                     4060 0.0362  
 5 Morphological anomaly                                   2644 0.0236  
 6 Clinical group                                           952 0.00848 
 7 Clinical syndrome                                        661 0.00589 
 8 Category                                                 479 0.00427 
 9 Particular clinical situation in a disease or syndrome   418 0.00372 
10 Biological anomaly                                        41 0.000365
11 Histopathological subtype                                 40 0.000356</code></pre>
</div>
</div>
<p>This was followed by checking out the distributions of HPO frequency to see which categories had the most and least number of counts.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>df_freq <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(<span class="st">`</span><span class="at">HPO frequency</span><span class="st">`</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n))</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>df_freq</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 2
  `HPO frequency`            n
  &lt;chr&gt;                  &lt;int&gt;
1 Occasional (29-5%)     41140
2 Frequent (79-30%)      37480
3 Very frequent (99-80%) 25892
4 Very rare (&lt;4-1%)       6414
5 Excluded (0%)            705
6 Obligate (100%)          610
7 &lt;NA&gt;                       2</code></pre>
</div>
</div>
<p>Results for rare disorders with obligate or 100% frequency in patient’s populations were then filtered, showing disorder type, HPO frequency and disorder name. Specifically, I wanted to find out the disorder names associated with the “Disease” disorder type with HPO frequency of “Obligate (100%)”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>df_freq_ob <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">Disorder type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Disease"</span>, <span class="st">`</span><span class="at">HPO frequency</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Obligate (100%)"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">`</span><span class="at">Disorder type</span><span class="st">`</span>, <span class="st">`</span><span class="at">HPO frequency</span><span class="st">`</span>, <span class="st">`</span><span class="at">Disorder name</span><span class="st">`</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>df_freq_ob</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 404 × 3
   `Disorder type` `HPO frequency` `Disorder name`                              
   &lt;chr&gt;           &lt;chr&gt;           &lt;chr&gt;                                        
 1 Disease         Obligate (100%) Retinoblastoma                               
 2 Disease         Obligate (100%) Parathyroid carcinoma                        
 3 Disease         Obligate (100%) Pituitary carcinoma                          
 4 Disease         Obligate (100%) Familial hypocalciuric hypercalcemia         
 5 Disease         Obligate (100%) Familial hypocalciuric hypercalcemia         
 6 Disease         Obligate (100%) Ravine syndrome                              
 7 Disease         Obligate (100%) Ravine syndrome                              
 8 Disease         Obligate (100%) Interstitial granulomatous dermatitis with a…
 9 Disease         Obligate (100%) Interstitial granulomatous dermatitis with a…
10 Disease         Obligate (100%) PLIN1-related familial partial lipodystrophy 
# … with 394 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<p>I’d then like to look into associated counts of appearance of each disorder name. When I cross-checked with the full dataset in table view, I’ve noted that the number of appearance of each disorder name is linked to the number of preferred HPO phenotype terms for each of these disorder types.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> df_freq_ob <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(<span class="st">`</span><span class="at">Disorder name</span><span class="st">`</span>) </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>df2 <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 239 × 2
   `Disorder name`                                                             n
   &lt;chr&gt;                                                                   &lt;int&gt;
 1 Autosomal recessive complex spastic paraplegia due to Kennedy pathway …    10
 2 STT3A-CDG                                                                   9
 3 STT3B-CDG                                                                   9
 4 Spastic paraplegia-Paget disease of bone syndrome                           8
 5 Oculocutaneous albinism type 5                                              7
 6 PLIN1-related familial partial lipodystrophy                                7
 7 Plummer-Vinson syndrome                                                     5
 8 SSR4-CDG                                                                    5
 9 Cholesterol-ester transfer protein deficiency                               4
10 Isolated follicle stimulating hormone deficiency                            4
# … with 229 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<p>To show this, let’s link preferred HPO terms to a disorder name such as this one, “Autosomal recessive complex spastic paraplegia due to Kennedy pathway dysfunction”, which had the “Disease” disorder type with obligate or 100% HPO frequency.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>df_disease <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">Disorder type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Disease"</span>, <span class="st">`</span><span class="at">HPO frequency</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Obligate (100%)"</span>, <span class="st">`</span><span class="at">Disorder name</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Autosomal recessive complex spastic paraplegia due to Kennedy pathway dysfunction"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">`</span><span class="at">Disorder type</span><span class="st">`</span>, <span class="st">`</span><span class="at">HPO frequency</span><span class="st">`</span>, <span class="st">`</span><span class="at">Disorder name</span><span class="st">`</span>, <span class="st">`</span><span class="at">Preferred HPO term</span><span class="st">`</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(df_disease)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 55%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Disorder type</th>
<th style="text-align: left;">HPO frequency</th>
<th style="text-align: left;">Disorder name</th>
<th style="text-align: left;">Preferred HPO term</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Disease</td>
<td style="text-align: left;">Obligate (100%)</td>
<td style="text-align: left;">Autosomal recessive complex spastic paraplegia due to Kennedy pathway dysfunction</td>
<td style="text-align: left;">Progressive spastic paraplegia</td>
</tr>
<tr class="even">
<td style="text-align: left;">Disease</td>
<td style="text-align: left;">Obligate (100%)</td>
<td style="text-align: left;">Autosomal recessive complex spastic paraplegia due to Kennedy pathway dysfunction</td>
<td style="text-align: left;">Microcephaly</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Disease</td>
<td style="text-align: left;">Obligate (100%)</td>
<td style="text-align: left;">Autosomal recessive complex spastic paraplegia due to Kennedy pathway dysfunction</td>
<td style="text-align: left;">Moderately short stature</td>
</tr>
<tr class="even">
<td style="text-align: left;">Disease</td>
<td style="text-align: left;">Obligate (100%)</td>
<td style="text-align: left;">Autosomal recessive complex spastic paraplegia due to Kennedy pathway dysfunction</td>
<td style="text-align: left;">Nasal, dysarthic speech</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Disease</td>
<td style="text-align: left;">Obligate (100%)</td>
<td style="text-align: left;">Autosomal recessive complex spastic paraplegia due to Kennedy pathway dysfunction</td>
<td style="text-align: left;">Delayed gross motor development</td>
</tr>
<tr class="even">
<td style="text-align: left;">Disease</td>
<td style="text-align: left;">Obligate (100%)</td>
<td style="text-align: left;">Autosomal recessive complex spastic paraplegia due to Kennedy pathway dysfunction</td>
<td style="text-align: left;">Progressive spasticity</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Disease</td>
<td style="text-align: left;">Obligate (100%)</td>
<td style="text-align: left;">Autosomal recessive complex spastic paraplegia due to Kennedy pathway dysfunction</td>
<td style="text-align: left;">Lower limb hyperreflexia</td>
</tr>
<tr class="even">
<td style="text-align: left;">Disease</td>
<td style="text-align: left;">Obligate (100%)</td>
<td style="text-align: left;">Autosomal recessive complex spastic paraplegia due to Kennedy pathway dysfunction</td>
<td style="text-align: left;">Ankle clonus</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Disease</td>
<td style="text-align: left;">Obligate (100%)</td>
<td style="text-align: left;">Autosomal recessive complex spastic paraplegia due to Kennedy pathway dysfunction</td>
<td style="text-align: left;">Retinal pigment epithelial mottling</td>
</tr>
<tr class="even">
<td style="text-align: left;">Disease</td>
<td style="text-align: left;">Obligate (100%)</td>
<td style="text-align: left;">Autosomal recessive complex spastic paraplegia due to Kennedy pathway dysfunction</td>
<td style="text-align: left;">Progressive spastic paraparesis</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>As shown in the dataframe above, under the column name, “Preferred HPO term”, there were a total of ten different HPO phenotype terms associated with this particular rare disease with 100% HPO frequency within the patient population for this specific type of spastic paraplegia.</p>
<p>By using similar filtering method, we could quickly narrow down any particular rare disease of interest to find out specific phenotype or clinical features, along with associated HPO phenotype frequency, for further investigations.</p>
<p>For “Malformation syndrome”, a similar search process was used to find out what was the most common phenotypes associated with it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>df_freq_ma <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">Disorder type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Malformation syndrome"</span>, <span class="st">`</span><span class="at">HPO frequency</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Obligate (100%)"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">`</span><span class="at">Disorder type</span><span class="st">`</span>, <span class="st">`</span><span class="at">HPO frequency</span><span class="st">`</span>, <span class="st">`</span><span class="at">Disorder name</span><span class="st">`</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>df_freq_ma</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 125 × 3
   `Disorder type`       `HPO frequency` `Disorder name`                  
   &lt;chr&gt;                 &lt;chr&gt;           &lt;chr&gt;                            
 1 Malformation syndrome Obligate (100%) CLAPO syndrome                   
 2 Malformation syndrome Obligate (100%) CLAPO syndrome                   
 3 Malformation syndrome Obligate (100%) Weaver-Williams syndrome         
 4 Malformation syndrome Obligate (100%) Weaver-Williams syndrome         
 5 Malformation syndrome Obligate (100%) Weaver-Williams syndrome         
 6 Malformation syndrome Obligate (100%) Weaver-Williams syndrome         
 7 Malformation syndrome Obligate (100%) Weaver-Williams syndrome         
 8 Malformation syndrome Obligate (100%) Weaver-Williams syndrome         
 9 Malformation syndrome Obligate (100%) Lethal recessive chondrodysplasia
10 Malformation syndrome Obligate (100%) Lethal recessive chondrodysplasia
# … with 115 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<p>Count() was used to find out the number of appearance of each disorder name in descending order.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>df3 <span class="ot">&lt;-</span> df_freq_ma <span class="sc">%&gt;%</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(<span class="st">`</span><span class="at">Disorder name</span><span class="st">`</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>df3 <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 40 × 2
   `Disorder name`                                                             n
   &lt;chr&gt;                                                                   &lt;int&gt;
 1 Hydrocephalus-obesity-hypogonadism syndrome                                12
 2 Pelviscapular dysplasia                                                    11
 3 46,XX disorder of sex development-skeletal anomalies syndrome               9
 4 X-linked microcephaly-growth retardation-prognathism-cryptorchidism sy…     9
 5 Severe intellectual disability-hypotonia-strabismus-coarse face-planov…     7
 6 Lethal recessive chondrodysplasia                                           6
 7 Weaver-Williams syndrome                                                    6
 8 SERKAL syndrome                                                             5
 9 Patent ductus arteriosus-bicuspid aortic valve-hand anomalies syndrome      4
10 46,XX gonadal dysgenesis                                                    3
# … with 30 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<p>To show one of the examples of the most common malformation syndrome with the most associated phenotypic features (with a total of 12 different phenotypic descriptions):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>df_mal_syn <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">Disorder type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Malformation syndrome"</span>, <span class="st">`</span><span class="at">HPO frequency</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Obligate (100%)"</span>, <span class="st">`</span><span class="at">Disorder name</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Hydrocephalus-obesity-hypogonadism syndrome"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">`</span><span class="at">Disorder type</span><span class="st">`</span>, <span class="st">`</span><span class="at">HPO frequency</span><span class="st">`</span>, <span class="st">`</span><span class="at">Disorder name</span><span class="st">`</span>, <span class="st">`</span><span class="at">Preferred HPO term</span><span class="st">`</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(df_mal_syn)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 19%">
<col style="width: 14%">
<col style="width: 38%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Disorder type</th>
<th style="text-align: left;">HPO frequency</th>
<th style="text-align: left;">Disorder name</th>
<th style="text-align: left;">Preferred HPO term</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Malformation syndrome</td>
<td style="text-align: left;">Obligate (100%)</td>
<td style="text-align: left;">Hydrocephalus-obesity-hypogonadism syndrome</td>
<td style="text-align: left;">Hydrocephalus</td>
</tr>
<tr class="even">
<td style="text-align: left;">Malformation syndrome</td>
<td style="text-align: left;">Obligate (100%)</td>
<td style="text-align: left;">Hydrocephalus-obesity-hypogonadism syndrome</td>
<td style="text-align: left;">Short neck</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Malformation syndrome</td>
<td style="text-align: left;">Obligate (100%)</td>
<td style="text-align: left;">Hydrocephalus-obesity-hypogonadism syndrome</td>
<td style="text-align: left;">Gynecomastia</td>
</tr>
<tr class="even">
<td style="text-align: left;">Malformation syndrome</td>
<td style="text-align: left;">Obligate (100%)</td>
<td style="text-align: left;">Hydrocephalus-obesity-hypogonadism syndrome</td>
<td style="text-align: left;">Hypergonadotropic hypogonadism</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Malformation syndrome</td>
<td style="text-align: left;">Obligate (100%)</td>
<td style="text-align: left;">Hydrocephalus-obesity-hypogonadism syndrome</td>
<td style="text-align: left;">Intellectual disability, mild</td>
</tr>
<tr class="even">
<td style="text-align: left;">Malformation syndrome</td>
<td style="text-align: left;">Obligate (100%)</td>
<td style="text-align: left;">Hydrocephalus-obesity-hypogonadism syndrome</td>
<td style="text-align: left;">Obesity</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Malformation syndrome</td>
<td style="text-align: left;">Obligate (100%)</td>
<td style="text-align: left;">Hydrocephalus-obesity-hypogonadism syndrome</td>
<td style="text-align: left;">Mitral valve prolapse</td>
</tr>
<tr class="even">
<td style="text-align: left;">Malformation syndrome</td>
<td style="text-align: left;">Obligate (100%)</td>
<td style="text-align: left;">Hydrocephalus-obesity-hypogonadism syndrome</td>
<td style="text-align: left;">Low posterior hairline</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Malformation syndrome</td>
<td style="text-align: left;">Obligate (100%)</td>
<td style="text-align: left;">Hydrocephalus-obesity-hypogonadism syndrome</td>
<td style="text-align: left;">High, narrow palate</td>
</tr>
<tr class="even">
<td style="text-align: left;">Malformation syndrome</td>
<td style="text-align: left;">Obligate (100%)</td>
<td style="text-align: left;">Hydrocephalus-obesity-hypogonadism syndrome</td>
<td style="text-align: left;">Cubitus valgus</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Malformation syndrome</td>
<td style="text-align: left;">Obligate (100%)</td>
<td style="text-align: left;">Hydrocephalus-obesity-hypogonadism syndrome</td>
<td style="text-align: left;">Short stature</td>
</tr>
<tr class="even">
<td style="text-align: left;">Malformation syndrome</td>
<td style="text-align: left;">Obligate (100%)</td>
<td style="text-align: left;">Hydrocephalus-obesity-hypogonadism syndrome</td>
<td style="text-align: left;">Short 4th metacarpal</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Now, to add one more piece of work towards this exploratory data analysis, I thought to check out the Validation date column. “Validation date” in this context meant the dates when the annotations of HPO terms were made for each rare disorder, which were based on the source articles listed (as shown in the Source column).</p>
<p>Firstly, I started with the “Disease” disorder type and singled out the year component from the Validation date column.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>df_val_date <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">year =</span> <span class="fu">year</span>(<span class="st">`</span><span class="at">Validation date</span><span class="st">`</span>), <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">abbr =</span> <span class="cn">FALSE</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>df_val_date</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 112,243 × 16
   Disorder gr…¹ Disor…² HPO d…³ Diagn…⁴ HPO f…⁵ HPO I…⁶ Prefe…⁷ Disor…⁸ Disor…⁹
   &lt;chr&gt;         &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt;
 1 Disorder      Disease      59 Diagno… Very f… HP:000… Pectus… Marfan…     558
 2 Disorder      Disease      59 Diagno… Very f… HP:000… Striae… Marfan…     558
 3 Disorder      Disease      59 Diagno… Very f… HP:000… Arachn… Marfan…     558
 4 Disorder      Disease      59 Diagno… Very f… HP:000… Dispro… Marfan…     558
 5 Disorder      Disease      59 Diagno… Very f… HP:000… Pes pl… Marfan…     558
 6 Disorder      Disease      59 Diagno… Very f… HP:000… Sponta… Marfan…     558
 7 Disorder      Disease      59 Diagno… Very f… HP:000… Dilata… Marfan…     558
 8 Disorder      Disease      59 Diagno… Freque… HP:000… Myopia  Marfan…     558
 9 Disorder      Disease      59 Diagno… Freque… HP:000… Dental… Marfan…     558
10 Disorder      Disease      59 Diagno… Freque… HP:000… Pectus… Marfan…     558
# … with 112,233 more rows, 7 more variables: Online &lt;chr&gt;, Source &lt;chr&gt;,
#   `Validation date` &lt;dttm&gt;, `Validation status` &lt;chr&gt;, year &lt;dbl&gt;,
#   label &lt;lgl&gt;, abbr &lt;lgl&gt;, and abbreviated variable names ¹​`Disorder group`,
#   ²​`Disorder type`, ³​`HPO disorder &amp; clinical entity association count`,
#   ⁴​`Diagnostic criteria`, ⁵​`HPO frequency`, ⁶​`HPO ID`, ⁷​`Preferred HPO term`,
#   ⁸​`Disorder name`, ⁹​`Disorder Orphacode`
# ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names</code></pre>
</div>
</div>
<p>To show this in a dataframe, observations for “Disease” disorder type were shown by using a filter:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>df_val_date_d <span class="ot">&lt;-</span> df_val_date <span class="sc">%&gt;%</span> </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">`</span><span class="at">Disorder type</span><span class="st">`</span>, year) <span class="sc">%&gt;%</span> </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">Disorder type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Disease"</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>df_val_date_d</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 57,920 × 2
   `Disorder type`  year
   &lt;chr&gt;           &lt;dbl&gt;
 1 Disease          2016
 2 Disease          2016
 3 Disease          2016
 4 Disease          2016
 5 Disease          2016
 6 Disease          2016
 7 Disease          2016
 8 Disease          2016
 9 Disease          2016
10 Disease          2016
# … with 57,910 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<p>Then to make it easier to visualise, the year counts were plotted in a bar graph. Interestingly, 2016 seemed to be the year for rare disorders to be annotated with the most phenotypic features (if referring back to the original dataset, each observation or row was present for a unique “Preferred HPO term” or phenotypic abnormality).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>df_val_date_d <span class="sc">%&gt;%</span> </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> year)) <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 49 rows containing non-finite values (stat_count).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="PhenotypesRareDiseases_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It was also worth noting that there were 49 rows of non-finite values excluded from the bar graph above. To look into this, a count on the year column of the dataframe df_val_date_d was done, which confirmed that these were the “NA” or missing values in the validation date column.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>df_val_date_d <span class="sc">%&gt;%</span> </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 2
   year     n
  &lt;dbl&gt; &lt;int&gt;
1  2015   567
2  2016 14193
3  2017  5419
4  2018  6297
5  2019 10525
6  2020  9402
7  2021 11468
8    NA    49</code></pre>
</div>
</div>
</section>
<section id="summary" class="level5">
<h5 class="anchored" data-anchor-id="summary"><strong>Summary</strong></h5>
<p>To quickly summarise key findings from this work<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> regarding phenotypes associated with rare diseases:</p>
<ul>
<li><strong>Autosomal recessive complex spastic paraplegia due to Kennedy pathway dysfunction</strong> was one of the most common rare diseases under the Disease disorder type with the most phenotypic abnormalities recorded, which were:</li>
</ul>
<ol type="1">
<li>progressive spastic paraplegia</li>
<li>microcephaly</li>
<li>moderately short stature</li>
<li>nasal, dysarthic speech</li>
<li>delayed gross motor development</li>
<li>progressive spasticity</li>
<li>lower limb hyperreflexia</li>
<li>ankle clonus</li>
<li>retinal pigment epithelial mottling</li>
<li>progressive spastic paraparesis</li>
</ol>
<ul>
<li>For malformation syndrome of the rare disorder type, <strong>Hydrocephalus-obesity-hypogonadism syndrome</strong> was found to be one of the most common rare diseases with the most phenotypic abnormalities recorded, which were:</li>
</ul>
<ol type="1">
<li>hydrocephalus</li>
<li>short neck</li>
<li>gynecomastia</li>
<li>hypergonadotropic hypogonadism</li>
<li>intellectual disability, mild</li>
<li>obesity</li>
<li>mitral valve prolapse</li>
<li>low posterior hairline</li>
<li>high, narrow palate</li>
<li>cubitus valgus</li>
<li>short stature</li>
<li>short 4th metacarpal</li>
</ol>
<ul>
<li>The year of 2016 had the highest number of HPO terms or phenotypic abnormalities annotated to rare disorders from specific named source articles, and on the contrary, 2015 had the lowest counts from the dataset</li>
</ul>


</section>


<div id="quarto-appendix" class="default"><section class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1" role="doc-endnote"><p>Used only for initial data cleaning stage - please see this <a href="https://github.com/jhylin/Portfolio-projects/blob/main/Phenotypes%20associated%20with%20rare%20diseases%20-%20initial%20data%20cleaning.ipynb">GitHub link</a> for details. R was used for the rest of the analysis<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2" role="doc-endnote"><p>This work is under <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0 International License</a> if anyone is interested in exploring the dataset further<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3" role="doc-endnote"><p>“Orphadata: Free access products description” - April 2020. http://www.orphadata.org/cgi-bin/img/PDF/OrphadataFreeAccessProductsDescription.pdf. Version 2<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4" role="doc-endnote"><p>It’s possible to dig further into the dataset e.g.&nbsp;diagnostic criterion and perhaps even bring back some of the columns removed initially, however due to time constraints (due to being a one-person team and also I’d like to start on the COVID-19 antiviral work soon), I’ll leave some room here for the interested to work on the data<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } 
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="jhylin/Data-analytics-and-research-blog" data-repo-id="R_kgDOHw7lGQ" data-category="General" data-category-id="DIC_kwDOHw7lGc4CQzQ_" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
      <div class="nav-footer-center">Blog made with <a href="https://quarto.org/">Quarto</a> 🧡 by Jennifer HY Lin ©2022</div>
  </div>
</footer>



</body></html>