---
title: Machine learning with ChEMBL small molecules
subtitle: Going deeper with *scikit-learn* 
author: Jennifer HY Lin
date: '2023-2-18'
draft: true
categories:
  - Machine learning projects
  - Polars
  - Python
  - ChEMBL database
  - Cheminformatics
jupyter: python3
---

##### ***Machine learning in drug discovery - series 2***

<br>

##### **Foreword**

***Feel free to skip this part as this is really me speaking my thoughts out loud***

After encountering several hiccups during my job hunt in data analytics lately (mainly domestic jobs in NZ), I think I need to make up my mind on which field I'm going for (I might be over-qualified for being a general health data analyst...). So here it is, I'm going to concentrate on using machine learning in Python, specifically in drug discovery field for a while. This is not to say I'm an expert in data analysis already, but I think I have some general understandings of different types of data analytical techniques available and the ones being used commonly. This will always be an important part that I'll keep coming back to practise and improve, but I'll be placing more emphasis on ML so that I can somehow create some ML experiences for myself, while trying to find a good match in the research and data science job market in the pharmaceutical field (which is actually my preferred way to gain actual, real-world ML experience, but alas I'll have to self-create some first to show that I can start doing it...). I also have a feeling that I may need to venture out into overseas roles in the near future, as these types of roles involving ML and pharmaceuticals are just too difficult to spot in NZ.

I once read a [blog post on learning ML](https://vickiboykis.com/2022/11/10/how-i-learn-machine-learning/) by V. Boykis, who had suggested to go broadly in topics, then go deep in one of them, which I've agreed wholeheartedly as the approach to go about in the tech world, since there is no way on earth that I will be able to learn everything completely (even OpenAI's ChatGPT has limits - being restricted by the amount and types of input data being fed into the training of the GPT). So since I've branched into 3 programming languages so far, I've decided not to expand further into new programming languages for now, to avoid being "half-bucket-full" for everything, I should really narrow down my focus now. To name the 3 programming languages I've learnt, in the order I've learnt them, it would be Python, R and Rust. In that, I'm most comfortable with Python as that was my first language, then it would be R, and for Rust, I'm practically a kindie student trying to explore. I think right now is a good time for me to go deep into an area that I know will matter a lot to me and has always grabbed my attention and interests ever since I've diverted into the research world previously.

<br>

##### **Introduction**

This post was really a continuation of the first series - Small molecules in ChEMBL database - in that I wanted to carry on with cross validation of the logistic regression model I've built in series 1.
