---
title: "Publications"
author: "Jennifer HY Lin"
date: "2022-01-24"
categories: [Research]
comments: false
---

Throughout my PhD, I've also collaborated with the lab group members and also other research groups in other academic research projects. The following publications[^1] were the ones I was involved in:

[^1]: Not a significantly large number of publications there, perhaps due to the research topics I've chosen, they tend to require months or years to see tangible results... so here is my very humble list as some others may be more productive than me...

-   Palanimuthu D, Poon R, Sahni S, Anjum R, Hibbs D, Lin JHY, Bernhardt PV, Kalinowski DS, Richardson DR. [A novel class of thiosemicarbazones show multi-functional activity for the treatment of Alzheimer's disease](https://pubmed.ncbi.nlm.nih.gov/28841514/). Eur J Med Chem. 2017; 139: 612-632. (IF = 4.816)

-   Panda D, Bhattacharya D, Gao QH, Oza PM, Lin JHY, Hawkins B, Hibbs DE, Groundwater PW. [Identification of agents targeting FtsZ assembly](https://pubmed.ncbi.nlm.nih.gov/27284850/). Future Med Chem. 2016; 8(10):1111-32. (IF = 3.969)

-   Gao Q, Hanh J, Váradi L, Cairns R, Sjöström H, Liao VW, Wood P, Balaban S, Ong JA, Lin JHY, Lai F, Hoy AJ, Grewal T, Groundwater PW, Hibbs DE. [Identification of dual PPARα/γ agonists and their effects on lipid metabolism](https://pubmed.ncbi.nlm.nih.gov/26616289/). Bioorg Med Chem. 2015; 23(24):7676-84. (IF = 2.881)
