---
title: Machine learning with ChEMBL small molecules
subtitle: Going deeper with *scikit-learn* 
author: Jennifer HY Lin
date: '2023-2-18'
draft: true
categories:
  - Machine learning projects
  - Polars
  - Python
  - ChEMBL database
  - Cheminformatics
jupyter: python3
---

##### ***Machine learning in drug discovery - series 2***

<br>

##### **Foreword**

After encountering several hiccups during my job hunt in data science lately, I think I need to make up my mind on which field I'm going for, so here it is, I'm going to concentrate on using machine learning in Python in drug discovery for a while. This is not to say I'm an expert in data analysis already, but I think I have a reasonable understandings of different types of data analytical techniques after spending about one year on it. I once read a blog post by Vicki Boykis, who had suggested to go broadly in topics, then go deep in one of them, which I've agreed wholeheartedly as the approach to go about the tech world, since there is no way on earth that I will be able to learn everything completely. So since I've branched in 3 programming languages now, to name them in the order I've learnt them would be: Python, R and Rust, I think right now is a good time for me to go deep into an area that I know will matter a lot to me and has always grabbed my attention and interests since my masters degree.

<br>

##### **Introduction**

This post is really a continuation of the first series - Small molecules in ChEMBL database - in that I wanted to carry on with cross validation of the logistic regression model I've built in series 1.
