---
title: "Natural history of rare diseases - malformation syndrome"
author: "Jennifer HY Lin"
date: "2022-06-27"
categories: [Data analytics projects, Python]
---

### **Introduction**

So my current interests are still in rare diseases from Orphanet website so the next focus is on natural history of rare diseases, specifically I'd like to focus on malformation syndrome[^1] for now. There are so much more data available on Orphanet, which I'd really like to look further into such as phenotypes associated with different rare diseases, so this is likely the next one I'll be working on.

[^1]: This project was last committed on 27th June 2022 on GitHub so I've set it as the published date, prior to the blog move. This work is under [CC BY-SA 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/) for anyone interested in exploring the topic further.


### **Project link**

The .ipynb file can be found in my GitHub repository of Portfolio-projects at this URL: [https://github.com/jhylin/Portfolio-projects](https://github.com/jhylin/Portfolio-projects) or go to this [link](https://github.com/jhylin/Portfolio-projects/blob/main/Natural%20history%20of%20rare%20disease%20-%20malformation%20syndrome.ipynb), which will take you to the Jupyter notebook for this work to show the differences in life spans for different rare diseases under this particular disorder type.


### **Summary**

-   Turner syndrome and Prune belly syndrome are the only two disorders of the malformation syndrome type that have an average age of onset at antenatal period, with an average age of death in the elderly years

-   This means these two rare disorders have had relatively long life spans out of all the rare diseases present in the dataset

-   Oppositely, there are far more rare disorders, such as Noonan syndrome, Trisomy 13, Hydraencephaly and more, with early childhood deaths while having the same antenatal onsets as Turner syndrome and Prune belly syndrome
