{
  "hash": "2455cb616d112b62ad05898186f37246",
  "result": {
    "markdown": "---\ntitle: Small molecules in ChEMBL database\nsubtitle: Series 1.1 - Polars dataframe library and machine learning in *scikit-learn*\nauthor: Jennifer HY Lin\ndate: 2023-1-4\ndraft: false\ncategories:\n  - Machine learning projects\n  - Scikit-learn\n  - Polars\n  - Python\n  - Jupyter\n  - ChEMBL database\n  - Cheminformatics\n---\n\n##### ***Machine learning in drug discovery - series 1.1***\n\n*The ML series has been re-numbered to reflect all 3 posts relevant to small molecules in ChEMBL database to avoid confusions*\n\n*Some of the code involving Polars dataframe library has been updated on 16th August 2023 due to updates to the package - please always refer to Polars API reference documentations for most up-to-date code*\n\n<br>\n\n##### **Background**\n\nAs my interests gradually grew for Rust, I realised why so many people said it might be a hard programming language to learn. My head was spinning after reading the Rust programming language book and watching a few online teaching videos about it. I then decided to start from something I was more familiar with, and somehow through various online ventures and searching, I've managed to start two projects in parallel. The first one was where I used Polars dataframe library, and the second one would be about using Rust through an interactive user interface such as Jupyter notebook. I've anticipated that the second project would take much longer time for me to finish, so I would be tackling the first project for now.\n\nThis project was about using Polars, a blazingly fast dataframe library that was written completely in Rust with a very light Python binding that was available for use via Python or Rust, so I started using Polars via Python on Jupyter Lab initially, which involved data wrangling, some exploratory data analysis (EDA), and a reasonably larger section on using machine learning (ML) through *scikit-learn*. The editing and publishing of this post was mainly achieved via RStudio IDE.\n\n<br>\n\n##### **Install Polars**\n\n::: {.cell execution_count=1}\n``` {.python .cell-code}\n# To install Polars dataframe library\n# Uncomment below to download and install Polars\n#!pip install polars\n\n# Update Polars version\n# Uncomment the line below to update Polars\n#!pip install --upgrade polars\n```\n:::\n\n\nOnce Polars was installed, the next step was to import it for use.\n\n::: {.cell execution_count=2}\n``` {.python .cell-code}\nimport polars as pl\n```\n:::\n\n\n::: {.cell execution_count=3}\n``` {.python .cell-code}\n# Show version of Polars\n# Uncomment line below to check version of Polars installed/updated\n#pl.show_versions()\n```\n:::\n\n\n<br>\n\n##### **Download dataset**\n\nThe dataset, which was purely about small molecules and their physicochemical properties, was downloaded from [ChEMBL database](https://www.ebi.ac.uk/chembl/) and saved as a .csv file. I've decided not to upload the \"chembl_mols.csv\" file due to its sheer size (around 0.6 GB), and also I'd like to stay using free open-source resources (including GitHub) at this stage. I've looked into the Git large file system, but for the free version it only provides 2 GB, which at this stage, I think by adding this larger than usual .csv file along with my portfolio blog repository may exceed this limit in no time.\n\nFor anyone who would like to use the same dataset, the file I used would be equivalent to a straight download from the home page of ChEMBL database, via clicking on the \"Distinct compounds\" (please see the circled area in the image below). Options were available to download the files as .csv, .tsv or .sdf formats (located at the top right of the page).\n\n<br>\n\n![Image adapted from ChEMBL database website](ChEMBL_cpds.jpg){fig-align=\"center\"}\n\n<br>\n\nOnce we've had the file ready, it would be read via the usual read_csv() method.\n\n::: {.cell execution_count=4}\n``` {.python .cell-code}\ndf = pl.read_csv(\"chembl_mols.csv\")\ndf.head() #read first 5 rows\n#df #read full dataset\n```\n\n::: {.cell-output .cell-output-display execution_count=50}\n```{=html}\n<div><style>\n.dataframe > thead > tr > th,\n.dataframe > tbody > tr > td {\n  text-align: right;\n}\n</style>\n<small>shape: (5, 1)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>ChEMBL ID&quot;;&quot;Name&quot;;&quot;Synonyms&quot;;&quot;Type&quot;;&quot;Max Phase&quot;;&quot;Molecular Weight&quot;;&quot;Targets&quot;;&quot;Bioactivities&quot;;&quot;AlogP&quot;;&quot;Polar Surface Area&quot;;&quot;HBA&quot;;&quot;HBD&quot;;&quot;#RO5 Violations&quot;;&quot;#Rotatable Bonds&quot;;&quot;Passes Ro3&quot;;&quot;QED Weighted&quot;;&quot;CX Acidic pKa&quot;;&quot;CX Basic pKa&quot;;&quot;CX LogP&quot;;&quot;CX LogD&quot;;&quot;Aromatic Rings&quot;;&quot;Structure Type&quot;;&quot;Inorganic Flag&quot;;&quot;Heavy Atoms&quot;;&quot;HBA (Lipinski)&quot;;&quot;HBD (Lipinski)&quot;;&quot;#RO5 Violations (Lipinski)&quot;;&quot;Molecular Weight (Monoisotopic)&quot;;&quot;Molecular Species&quot;;&quot;Molecular Formula&quot;;&quot;Smiles&quot;;&quot;Inchi Key</th></tr><tr><td>str</td></tr></thead><tbody><tr><td>&quot;CHEMBL1206185;…</td></tr><tr><td>&quot;CHEMBL539070;&quot;…</td></tr><tr><td>&quot;CHEMBL3335528;…</td></tr><tr><td>&quot;CHEMBL2419030;…</td></tr><tr><td>&quot;CHEMBL4301448;…</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n<br>\n\n##### **Data wrangling**\n\nNow, since this dataset was downloaded as a .csv file, this meant it was likely to have a certain delimiter between each variable. So the whole dataset was presented as strings where each string represented each compound in each row. Each variable was separated by semicolons. To read it properly, I've added a delimiter term in the code to transform the dataframe into a more readable format.\n\n::: {.cell execution_count=5}\n``` {.python .cell-code}\n# By referring to Polars documentation, \n# use \"sep\" to set the delimiter of the file\n# which was semicolons in this case\ndf = pl.read_csv(\"chembl_mols.csv\", separator = \";\")\n# Show the first 10 rows of data\n#df.head(10)\n# or full dataset\ndf\n```\n\n::: {.cell-output .cell-output-display execution_count=51}\n```{=html}\n<div><style>\n.dataframe > thead > tr > th,\n.dataframe > tbody > tr > td {\n  text-align: right;\n}\n</style>\n<small>shape: (2_331_700, 32)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>ChEMBL ID</th><th>Name</th><th>Synonyms</th><th>Type</th><th>Max Phase</th><th>Molecular Weight</th><th>Targets</th><th>Bioactivities</th><th>AlogP</th><th>Polar Surface Area</th><th>HBA</th><th>HBD</th><th>#RO5 Violations</th><th>#Rotatable Bonds</th><th>Passes Ro3</th><th>QED Weighted</th><th>CX Acidic pKa</th><th>CX Basic pKa</th><th>CX LogP</th><th>CX LogD</th><th>Aromatic Rings</th><th>Structure Type</th><th>Inorganic Flag</th><th>Heavy Atoms</th><th>HBA (Lipinski)</th><th>HBD (Lipinski)</th><th>#RO5 Violations (Lipinski)</th><th>Molecular Weight (Monoisotopic)</th><th>Molecular Species</th><th>Molecular Formula</th><th>Smiles</th><th>Inchi Key</th></tr><tr><td>str</td><td>str</td><td>str</td><td>str</td><td>i64</td><td>str</td><td>str</td><td>str</td><td>str</td><td>str</td><td>str</td><td>str</td><td>str</td><td>str</td><td>str</td><td>str</td><td>str</td><td>str</td><td>str</td><td>str</td><td>str</td><td>str</td><td>i64</td><td>str</td><td>str</td><td>str</td><td>str</td><td>str</td><td>str</td><td>str</td><td>str</td><td>str</td></tr></thead><tbody><tr><td>&quot;CHEMBL1206185&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>&quot;607.88&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;9.46&quot;</td><td>&quot;89.62&quot;</td><td>&quot;5&quot;</td><td>&quot;2&quot;</td><td>&quot;2&quot;</td><td>&quot;17&quot;</td><td>&quot;N&quot;</td><td>&quot;0.09&quot;</td><td>&quot;-1.91&quot;</td><td>&quot;8.38&quot;</td><td>&quot;9.40&quot;</td><td>&quot;9.36&quot;</td><td>&quot;3&quot;</td><td>&quot;MOL&quot;</td><td>-1</td><td>&quot;42&quot;</td><td>&quot;5&quot;</td><td>&quot;3&quot;</td><td>&quot;2&quot;</td><td>&quot;607.2790&quot;</td><td>&quot;ACID&quot;</td><td>&quot;C35H45NO4S2&quot;</td><td>&quot;CCCCCCCCCCC#CC…</td><td>&quot;UFBLKYIDZFRLPR…</td></tr><tr><td>&quot;CHEMBL539070&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>&quot;286.79&quot;</td><td>&quot;1&quot;</td><td>&quot;1&quot;</td><td>&quot;2.28&quot;</td><td>&quot;73.06&quot;</td><td>&quot;6&quot;</td><td>&quot;2&quot;</td><td>&quot;0&quot;</td><td>&quot;5&quot;</td><td>&quot;N&quot;</td><td>&quot;0.63&quot;</td><td>&quot;13.84&quot;</td><td>&quot;3.64&quot;</td><td>&quot;2.57&quot;</td><td>&quot;2.57&quot;</td><td>&quot;2&quot;</td><td>&quot;MOL&quot;</td><td>-1</td><td>&quot;17&quot;</td><td>&quot;5&quot;</td><td>&quot;3&quot;</td><td>&quot;0&quot;</td><td>&quot;250.0888&quot;</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C11H15ClN4OS&quot;</td><td>&quot;CCCOc1ccccc1-c…</td><td>&quot;WPEWNRKLKLNLSO…</td></tr><tr><td>&quot;CHEMBL3335528&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>&quot;842.80&quot;</td><td>&quot;2&quot;</td><td>&quot;6&quot;</td><td>&quot;0.18&quot;</td><td>&quot;269.57&quot;</td><td>&quot;18&quot;</td><td>&quot;5&quot;</td><td>&quot;2&quot;</td><td>&quot;17&quot;</td><td>&quot;N&quot;</td><td>&quot;0.09&quot;</td><td>&quot;3.20&quot;</td><td>&quot;None&quot;</td><td>&quot;3.31&quot;</td><td>&quot;-0.14&quot;</td><td>&quot;3&quot;</td><td>&quot;MOL&quot;</td><td>-1</td><td>&quot;60&quot;</td><td>&quot;19&quot;</td><td>&quot;5&quot;</td><td>&quot;2&quot;</td><td>&quot;842.2633&quot;</td><td>&quot;ACID&quot;</td><td>&quot;C41H46O19&quot;</td><td>&quot;COC(=O)[C@H](O…</td><td>&quot;KGUJQZWYZPYYRZ…</td></tr><tr><td>&quot;CHEMBL2419030&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>&quot;359.33&quot;</td><td>&quot;4&quot;</td><td>&quot;4&quot;</td><td>&quot;3.94&quot;</td><td>&quot;85.13&quot;</td><td>&quot;6&quot;</td><td>&quot;1&quot;</td><td>&quot;0&quot;</td><td>&quot;3&quot;</td><td>&quot;N&quot;</td><td>&quot;0.66&quot;</td><td>&quot;None&quot;</td><td>&quot;None&quot;</td><td>&quot;3.66&quot;</td><td>&quot;3.66&quot;</td><td>&quot;2&quot;</td><td>&quot;MOL&quot;</td><td>-1</td><td>&quot;24&quot;</td><td>&quot;6&quot;</td><td>&quot;1&quot;</td><td>&quot;0&quot;</td><td>&quot;359.0551&quot;</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C14H12F3N3O3S&quot;</td><td>&quot;O=c1nc(NC2CCCC…</td><td>&quot;QGDMYSDFCXOKML…</td></tr><tr><td>&quot;CHEMBL4301448&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>&quot;465.55&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;5.09&quot;</td><td>&quot;105.28&quot;</td><td>&quot;6&quot;</td><td>&quot;4&quot;</td><td>&quot;1&quot;</td><td>&quot;10&quot;</td><td>&quot;N&quot;</td><td>&quot;0.15&quot;</td><td>&quot;None&quot;</td><td>&quot;12.14&quot;</td><td>&quot;4.41&quot;</td><td>&quot;2.00&quot;</td><td>&quot;4&quot;</td><td>&quot;MOL&quot;</td><td>-1</td><td>&quot;33&quot;</td><td>&quot;7&quot;</td><td>&quot;5&quot;</td><td>&quot;1&quot;</td><td>&quot;465.1635&quot;</td><td>&quot;BASE&quot;</td><td>&quot;C24H24FN5O2S&quot;</td><td>&quot;N=C(N)NCCCOc1c…</td><td>&quot;RXTJPHLPHOZLFS…</td></tr><tr><td>&quot;CHEMBL3827271&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>&quot;712.85&quot;</td><td>&quot;1&quot;</td><td>&quot;1&quot;</td><td>&quot;-2.84&quot;</td><td>&quot;319.06&quot;</td><td>&quot;10&quot;</td><td>&quot;11&quot;</td><td>&quot;2&quot;</td><td>&quot;16&quot;</td><td>&quot;N&quot;</td><td>&quot;0.07&quot;</td><td>&quot;4.08&quot;</td><td>&quot;10.49&quot;</td><td>&quot;-6.88&quot;</td><td>&quot;-8.95&quot;</td><td>&quot;0&quot;</td><td>&quot;MOL&quot;</td><td>-1</td><td>&quot;50&quot;</td><td>&quot;19&quot;</td><td>&quot;14&quot;</td><td>&quot;3&quot;</td><td>&quot;712.4232&quot;</td><td>&quot;ZWITTERION&quot;</td><td>&quot;C31H56N10O9&quot;</td><td>&quot;CC(C)C[C@@H]1N…</td><td>&quot;QJQNNLICZLLPMB…</td></tr><tr><td>&quot;CHEMBL1969944&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>&quot;&quot;</td><td>&quot;56&quot;</td><td>&quot;56&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;NONE&quot;</td><td>-1</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td></tr><tr><td>&quot;CHEMBL3465961&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>&quot;319.42&quot;</td><td>&quot;16&quot;</td><td>&quot;22&quot;</td><td>&quot;2.22&quot;</td><td>&quot;50.50&quot;</td><td>&quot;4&quot;</td><td>&quot;1&quot;</td><td>&quot;0&quot;</td><td>&quot;6&quot;</td><td>&quot;N&quot;</td><td>&quot;0.87&quot;</td><td>&quot;None&quot;</td><td>&quot;9.38&quot;</td><td>&quot;2.13&quot;</td><td>&quot;-0.44&quot;</td><td>&quot;1&quot;</td><td>&quot;MOL&quot;</td><td>-1</td><td>&quot;23&quot;</td><td>&quot;4&quot;</td><td>&quot;1&quot;</td><td>&quot;0&quot;</td><td>&quot;319.2060&quot;</td><td>&quot;BASE&quot;</td><td>&quot;C18H26FN3O&quot;</td><td>&quot;CC(O)CN1CCC(CN…</td><td>&quot;FZEVYCHTADTXPM…</td></tr><tr><td>&quot;CHEMBL587495&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>&quot;478.54&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;6.85&quot;</td><td>&quot;66.73&quot;</td><td>&quot;4&quot;</td><td>&quot;3&quot;</td><td>&quot;1&quot;</td><td>&quot;6&quot;</td><td>&quot;N&quot;</td><td>&quot;0.23&quot;</td><td>&quot;10.67&quot;</td><td>&quot;8.47&quot;</td><td>&quot;6.04&quot;</td><td>&quot;4.93&quot;</td><td>&quot;5&quot;</td><td>&quot;MOL&quot;</td><td>-1</td><td>&quot;34&quot;</td><td>&quot;4&quot;</td><td>&quot;4&quot;</td><td>&quot;1&quot;</td><td>&quot;478.1439&quot;</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C26H21F3N4S&quot;</td><td>&quot;Nc1cccc(CNCc2c…</td><td>&quot;KZOHKPSNJBXTRJ…</td></tr><tr><td>&quot;CHEMBL3824158&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>&quot;422.48&quot;</td><td>&quot;2&quot;</td><td>&quot;4&quot;</td><td>&quot;5.09&quot;</td><td>&quot;109.54&quot;</td><td>&quot;6&quot;</td><td>&quot;2&quot;</td><td>&quot;1&quot;</td><td>&quot;10&quot;</td><td>&quot;N&quot;</td><td>&quot;0.31&quot;</td><td>&quot;4.59&quot;</td><td>&quot;7.99&quot;</td><td>&quot;2.49&quot;</td><td>&quot;2.42&quot;</td><td>&quot;2&quot;</td><td>&quot;MOL&quot;</td><td>-1</td><td>&quot;31&quot;</td><td>&quot;7&quot;</td><td>&quot;2&quot;</td><td>&quot;1&quot;</td><td>&quot;422.1842&quot;</td><td>&quot;ACID&quot;</td><td>&quot;C24H26N2O5&quot;</td><td>&quot;CCCCCCCNC(C1=C…</td><td>&quot;AXOVDUYYBUYLPC…</td></tr><tr><td>&quot;CHEMBL194112&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>&quot;366.38&quot;</td><td>&quot;2&quot;</td><td>&quot;3&quot;</td><td>&quot;4.80&quot;</td><td>&quot;57.53&quot;</td><td>&quot;3&quot;</td><td>&quot;2&quot;</td><td>&quot;0&quot;</td><td>&quot;1&quot;</td><td>&quot;N&quot;</td><td>&quot;0.75&quot;</td><td>&quot;8.98&quot;</td><td>&quot;None&quot;</td><td>&quot;4.84&quot;</td><td>&quot;4.83&quot;</td><td>&quot;1&quot;</td><td>&quot;MOL&quot;</td><td>-1</td><td>&quot;26&quot;</td><td>&quot;3&quot;</td><td>&quot;2&quot;</td><td>&quot;0&quot;</td><td>&quot;366.1443&quot;</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C20H21F3O3&quot;</td><td>&quot;C[C@]12CCC3c4c…</td><td>&quot;FIBOSLUEJGPVMK…</td></tr><tr><td>&quot;CHEMBL2047226&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>&quot;452.40&quot;</td><td>&quot;4&quot;</td><td>&quot;8&quot;</td><td>&quot;4.93&quot;</td><td>&quot;53.08&quot;</td><td>&quot;5&quot;</td><td>&quot;2&quot;</td><td>&quot;0&quot;</td><td>&quot;7&quot;</td><td>&quot;N&quot;</td><td>&quot;0.53&quot;</td><td>&quot;None&quot;</td><td>&quot;8.47&quot;</td><td>&quot;4.51&quot;</td><td>&quot;3.29&quot;</td><td>&quot;3&quot;</td><td>&quot;MOL&quot;</td><td>-1</td><td>&quot;29&quot;</td><td>&quot;5&quot;</td><td>&quot;2&quot;</td><td>&quot;0&quot;</td><td>&quot;451.1372&quot;</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C23H26BrN5&quot;</td><td>&quot;Brc1ccc(CNc2cc…</td><td>&quot;WOAVNWHCIXCOIZ…</td></tr><tr><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td></tr><tr><td>&quot;CHEMBL387315&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>&quot;673.99&quot;</td><td>&quot;2&quot;</td><td>&quot;2&quot;</td><td>&quot;9.83&quot;</td><td>&quot;43.86&quot;</td><td>&quot;3&quot;</td><td>&quot;0&quot;</td><td>&quot;2&quot;</td><td>&quot;21&quot;</td><td>&quot;N&quot;</td><td>&quot;0.08&quot;</td><td>&quot;None&quot;</td><td>&quot;9.57&quot;</td><td>&quot;10.60&quot;</td><td>&quot;8.45&quot;</td><td>&quot;4&quot;</td><td>&quot;MOL&quot;</td><td>-1</td><td>&quot;50&quot;</td><td>&quot;5&quot;</td><td>&quot;0&quot;</td><td>&quot;2&quot;</td><td>&quot;673.4607&quot;</td><td>&quot;BASE&quot;</td><td>&quot;C45H59N3O2&quot;</td><td>&quot;CCCCCc1ccc(C(=…</td><td>&quot;HVSKDFHVTFRADD…</td></tr><tr><td>&quot;CHEMBL540121&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>&quot;540.05&quot;</td><td>&quot;2&quot;</td><td>&quot;3&quot;</td><td>&quot;2.39&quot;</td><td>&quot;147.14&quot;</td><td>&quot;6&quot;</td><td>&quot;4&quot;</td><td>&quot;1&quot;</td><td>&quot;8&quot;</td><td>&quot;N&quot;</td><td>&quot;0.22&quot;</td><td>&quot;5.02&quot;</td><td>&quot;11.48&quot;</td><td>&quot;-0.75&quot;</td><td>&quot;-0.78&quot;</td><td>&quot;4&quot;</td><td>&quot;MOL&quot;</td><td>-1</td><td>&quot;36&quot;</td><td>&quot;9&quot;</td><td>&quot;5&quot;</td><td>&quot;1&quot;</td><td>&quot;503.1627&quot;</td><td>&quot;ZWITTERION&quot;</td><td>&quot;C26H26ClN5O4S&quot;</td><td>&quot;Cc1ccn(NS(=O)(…</td><td>&quot;TZLGWENJAJXWGA…</td></tr><tr><td>&quot;CHEMBL2387650&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>&quot;496.01&quot;</td><td>&quot;2&quot;</td><td>&quot;13&quot;</td><td>&quot;6.03&quot;</td><td>&quot;66.84&quot;</td><td>&quot;5&quot;</td><td>&quot;1&quot;</td><td>&quot;1&quot;</td><td>&quot;7&quot;</td><td>&quot;N&quot;</td><td>&quot;0.32&quot;</td><td>&quot;3.57&quot;</td><td>&quot;None&quot;</td><td>&quot;6.77&quot;</td><td>&quot;3.42&quot;</td><td>&quot;3&quot;</td><td>&quot;MOL&quot;</td><td>-1</td><td>&quot;33&quot;</td><td>&quot;5&quot;</td><td>&quot;1&quot;</td><td>&quot;1&quot;</td><td>&quot;495.0366&quot;</td><td>&quot;ACID&quot;</td><td>&quot;C25H18ClNO4S2&quot;</td><td>&quot;O=C(O)[C@@H](C…</td><td>&quot;LSYQEQADGPAMNF…</td></tr><tr><td>&quot;CHEMBL374041&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>&quot;504.50&quot;</td><td>&quot;2&quot;</td><td>&quot;4&quot;</td><td>&quot;3.04&quot;</td><td>&quot;144.95&quot;</td><td>&quot;8&quot;</td><td>&quot;3&quot;</td><td>&quot;1&quot;</td><td>&quot;10&quot;</td><td>&quot;N&quot;</td><td>&quot;0.28&quot;</td><td>&quot;6.59&quot;</td><td>&quot;4.37&quot;</td><td>&quot;2.17&quot;</td><td>&quot;1.33&quot;</td><td>&quot;3&quot;</td><td>&quot;MOL&quot;</td><td>-1</td><td>&quot;37&quot;</td><td>&quot;11&quot;</td><td>&quot;3&quot;</td><td>&quot;2&quot;</td><td>&quot;504.1645&quot;</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C26H24N4O7&quot;</td><td>&quot;CCOCCC1(Oc2ccc…</td><td>&quot;ABCSNHDQYHOLOO…</td></tr><tr><td>&quot;CHEMBL394794&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>&quot;707.86&quot;</td><td>&quot;1&quot;</td><td>&quot;2&quot;</td><td>&quot;4.31&quot;</td><td>&quot;183.99&quot;</td><td>&quot;12&quot;</td><td>&quot;3&quot;</td><td>&quot;2&quot;</td><td>&quot;9&quot;</td><td>&quot;N&quot;</td><td>&quot;0.18&quot;</td><td>&quot;12.10&quot;</td><td>&quot;None&quot;</td><td>&quot;3.09&quot;</td><td>&quot;3.09&quot;</td><td>&quot;0&quot;</td><td>&quot;MOL&quot;</td><td>-1</td><td>&quot;50&quot;</td><td>&quot;13&quot;</td><td>&quot;3&quot;</td><td>&quot;2&quot;</td><td>&quot;707.3881&quot;</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C37H57NO12&quot;</td><td>&quot;C=C1[C@@H](O)C…</td><td>&quot;CFMSPOHWBQUTHN…</td></tr><tr><td>&quot;CHEMBL2035815&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>&quot;534.89&quot;</td><td>&quot;10&quot;</td><td>&quot;10&quot;</td><td>&quot;4.46&quot;</td><td>&quot;146.01&quot;</td><td>&quot;10&quot;</td><td>&quot;3&quot;</td><td>&quot;1&quot;</td><td>&quot;8&quot;</td><td>&quot;N&quot;</td><td>&quot;0.28&quot;</td><td>&quot;None&quot;</td><td>&quot;6.22&quot;</td><td>&quot;3.48&quot;</td><td>&quot;3.48&quot;</td><td>&quot;4&quot;</td><td>&quot;MOL&quot;</td><td>-1</td><td>&quot;37&quot;</td><td>&quot;11&quot;</td><td>&quot;4&quot;</td><td>&quot;2&quot;</td><td>&quot;534.1142&quot;</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C22H18ClF3N8O3…</td><td>&quot;C=CC(=O)NCc1co…</td><td>&quot;ZRZKVZZVULTROL…</td></tr><tr><td>&quot;CHEMBL1586325&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>&quot;425.47&quot;</td><td>&quot;6&quot;</td><td>&quot;7&quot;</td><td>&quot;3.11&quot;</td><td>&quot;109.62&quot;</td><td>&quot;5&quot;</td><td>&quot;1&quot;</td><td>&quot;0&quot;</td><td>&quot;8&quot;</td><td>&quot;N&quot;</td><td>&quot;0.44&quot;</td><td>&quot;13.84&quot;</td><td>&quot;None&quot;</td><td>&quot;3.24&quot;</td><td>&quot;3.24&quot;</td><td>&quot;3&quot;</td><td>&quot;MOL&quot;</td><td>-1</td><td>&quot;30&quot;</td><td>&quot;8&quot;</td><td>&quot;1&quot;</td><td>&quot;0&quot;</td><td>&quot;425.1045&quot;</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C21H19N3O5S&quot;</td><td>&quot;O=C(CN(c1cccc(…</td><td>&quot;XVDMUGUIAWGPNU…</td></tr><tr><td>&quot;CHEMBL2017916&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>&quot;312.35&quot;</td><td>&quot;3&quot;</td><td>&quot;3&quot;</td><td>&quot;2.86&quot;</td><td>&quot;77.00&quot;</td><td>&quot;6&quot;</td><td>&quot;1&quot;</td><td>&quot;0&quot;</td><td>&quot;4&quot;</td><td>&quot;N&quot;</td><td>&quot;0.80&quot;</td><td>&quot;8.13&quot;</td><td>&quot;3.49&quot;</td><td>&quot;2.17&quot;</td><td>&quot;2.10&quot;</td><td>&quot;3&quot;</td><td>&quot;MOL&quot;</td><td>-1</td><td>&quot;22&quot;</td><td>&quot;6&quot;</td><td>&quot;1&quot;</td><td>&quot;0&quot;</td><td>&quot;312.0681&quot;</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C15H12N4O2S&quot;</td><td>&quot;COc1ccc(-c2nnc…</td><td>&quot;XIZUJGDKNPVNQA…</td></tr><tr><td>&quot;CHEMBL374652&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>&quot;403.83&quot;</td><td>&quot;1&quot;</td><td>&quot;1&quot;</td><td>&quot;5.98&quot;</td><td>&quot;36.02&quot;</td><td>&quot;2&quot;</td><td>&quot;2&quot;</td><td>&quot;1&quot;</td><td>&quot;4&quot;</td><td>&quot;N&quot;</td><td>&quot;0.42&quot;</td><td>&quot;13.65&quot;</td><td>&quot;None&quot;</td><td>&quot;5.36&quot;</td><td>&quot;5.36&quot;</td><td>&quot;3&quot;</td><td>&quot;MOL&quot;</td><td>-1</td><td>&quot;26&quot;</td><td>&quot;2&quot;</td><td>&quot;2&quot;</td><td>&quot;1&quot;</td><td>&quot;403.0421&quot;</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C18H14ClF4NOS&quot;</td><td>&quot;CC(O)(CSc1ccc(…</td><td>&quot;CRPQTBRTHURKII…</td></tr><tr><td>&quot;CHEMBL1416264&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>&quot;380.41&quot;</td><td>&quot;6&quot;</td><td>&quot;8&quot;</td><td>&quot;3.06&quot;</td><td>&quot;85.07&quot;</td><td>&quot;7&quot;</td><td>&quot;1&quot;</td><td>&quot;0&quot;</td><td>&quot;5&quot;</td><td>&quot;N&quot;</td><td>&quot;0.54&quot;</td><td>&quot;13.85&quot;</td><td>&quot;3.86&quot;</td><td>&quot;2.47&quot;</td><td>&quot;2.47&quot;</td><td>&quot;4&quot;</td><td>&quot;MOL&quot;</td><td>-1</td><td>&quot;27&quot;</td><td>&quot;7&quot;</td><td>&quot;1&quot;</td><td>&quot;0&quot;</td><td>&quot;380.0856&quot;</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C18H13FN6OS&quot;</td><td>&quot;O=C(CSc1ccc2nn…</td><td>&quot;QVYIEKHEJKFNAT…</td></tr><tr><td>&quot;CHEMBL213734&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>&quot;288.26&quot;</td><td>&quot;2&quot;</td><td>&quot;3&quot;</td><td>&quot;2.32&quot;</td><td>&quot;101.70&quot;</td><td>&quot;5&quot;</td><td>&quot;2&quot;</td><td>&quot;0&quot;</td><td>&quot;5&quot;</td><td>&quot;N&quot;</td><td>&quot;0.50&quot;</td><td>&quot;7.20&quot;</td><td>&quot;None&quot;</td><td>&quot;2.36&quot;</td><td>&quot;1.95&quot;</td><td>&quot;2&quot;</td><td>&quot;MOL&quot;</td><td>-1</td><td>&quot;21&quot;</td><td>&quot;7&quot;</td><td>&quot;2&quot;</td><td>&quot;0&quot;</td><td>&quot;288.0746&quot;</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C14H12N2O5&quot;</td><td>&quot;O=C(COc1ccccc1…</td><td>&quot;PZTWAHGBGTWVEB…</td></tr><tr><td>&quot;CHEMBL1531634&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>&quot;320.16&quot;</td><td>&quot;19&quot;</td><td>&quot;21&quot;</td><td>&quot;4.40&quot;</td><td>&quot;29.10&quot;</td><td>&quot;2&quot;</td><td>&quot;1&quot;</td><td>&quot;0&quot;</td><td>&quot;4&quot;</td><td>&quot;N&quot;</td><td>&quot;0.67&quot;</td><td>&quot;None&quot;</td><td>&quot;None&quot;</td><td>&quot;4.04&quot;</td><td>&quot;4.04&quot;</td><td>&quot;2&quot;</td><td>&quot;MOL&quot;</td><td>-1</td><td>&quot;19&quot;</td><td>&quot;2&quot;</td><td>&quot;1&quot;</td><td>&quot;0&quot;</td><td>&quot;319.0008&quot;</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C15H11BrFNO&quot;</td><td>&quot;O=C(/C=C/Nc1cc…</td><td>&quot;DKPWCCDDKFLKEC…</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n<br>\n\nInitially, I only wanted to download around 24 compounds from the ChEMBL database first. Unknowingly, I ended up downloading the whole curated set of 2,331,700 small molecules (!), and I found this out when I loaded the dataframe after setting up the delimiter for the csv file, which later led to the file size problem mentioned earlier.\n\nLoading these 2,331,700 rows of data was fast, which occurred within a few seconds without exaggeration. This echoed many users' experiences with Polars, so this was another nice surprise, and once again confirmed that Rust, and also Apache arrow, which was used as Polars' foundation, were solid in speed.\n\nNow I had the full dataframe, and I wanted to find out what types of physicochemical properties were there for the compounds.\n\n::: {.cell execution_count=6}\n``` {.python .cell-code}\n# Print all column names and data types \nprint(df.glimpse())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 2331700\nColumns: 32\n$ ChEMBL ID                       <str> CHEMBL1206185, CHEMBL539070, CHEMBL3335528, CHEMBL2419030, CHEMBL4301448, CHEMBL3827271, CHEMBL1969944, CHEMBL3465961, CHEMBL587495, CHEMBL3824158\n$ Name                            <str> , , , , , , , , , \n$ Synonyms                        <str> , , , , , , , , , \n$ Type                            <str> Small molecule, Small molecule, Small molecule, Small molecule, Small molecule, Small molecule, Small molecule, Small molecule, Small molecule, Small molecule\n$ Max Phase                       <i64> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0\n$ Molecular Weight                <str> 607.88, 286.79, 842.80, 359.33, 465.55, 712.85, , 319.42, 478.54, 422.48\n$ Targets                         <str> , 1, 2, 4, , 1, 56, 16, , 2\n$ Bioactivities                   <str> , 1, 6, 4, , 1, 56, 22, , 4\n$ AlogP                           <str> 9.46, 2.28, 0.18, 3.94, 5.09, -2.84, , 2.22, 6.85, 5.09\n$ Polar Surface Area              <str> 89.62, 73.06, 269.57, 85.13, 105.28, 319.06, , 50.50, 66.73, 109.54\n$ HBA                             <str> 5, 6, 18, 6, 6, 10, , 4, 4, 6\n$ HBD                             <str> 2, 2, 5, 1, 4, 11, , 1, 3, 2\n$ #RO5 Violations                 <str> 2, 0, 2, 0, 1, 2, , 0, 1, 1\n$ #Rotatable Bonds                <str> 17, 5, 17, 3, 10, 16, , 6, 6, 10\n$ Passes Ro3                      <str> N, N, N, N, N, N, , N, N, N\n$ QED Weighted                    <str> 0.09, 0.63, 0.09, 0.66, 0.15, 0.07, , 0.87, 0.23, 0.31\n$ CX Acidic pKa                   <str> -1.91, 13.84, 3.20, None, None, 4.08, , None, 10.67, 4.59\n$ CX Basic pKa                    <str> 8.38, 3.64, None, None, 12.14, 10.49, , 9.38, 8.47, 7.99\n$ CX LogP                         <str> 9.40, 2.57, 3.31, 3.66, 4.41, -6.88, , 2.13, 6.04, 2.49\n$ CX LogD                         <str> 9.36, 2.57, -0.14, 3.66, 2.00, -8.95, , -0.44, 4.93, 2.42\n$ Aromatic Rings                  <str> 3, 2, 3, 2, 4, 0, , 1, 5, 2\n$ Structure Type                  <str> MOL, MOL, MOL, MOL, MOL, MOL, NONE, MOL, MOL, MOL\n$ Inorganic Flag                  <i64> -1, -1, -1, -1, -1, -1, -1, -1, -1, -1\n$ Heavy Atoms                     <str> 42, 17, 60, 24, 33, 50, , 23, 34, 31\n$ HBA (Lipinski)                  <str> 5, 5, 19, 6, 7, 19, , 4, 4, 7\n$ HBD (Lipinski)                  <str> 3, 3, 5, 1, 5, 14, , 1, 4, 2\n$ #RO5 Violations (Lipinski)      <str> 2, 0, 2, 0, 1, 3, , 0, 1, 1\n$ Molecular Weight (Monoisotopic) <str> 607.2790, 250.0888, 842.2633, 359.0551, 465.1635, 712.4232, , 319.2060, 478.1439, 422.1842\n$ Molecular Species               <str> ACID, NEUTRAL, ACID, NEUTRAL, BASE, ZWITTERION, , BASE, NEUTRAL, ACID\n$ Molecular Formula               <str> C35H45NO4S2, C11H15ClN4OS, C41H46O19, C14H12F3N3O3S, C24H24FN5O2S, C31H56N10O9, , C18H26FN3O, C26H21F3N4S, C24H26N2O5\n$ Smiles                          <str> CCCCCCCCCCC#CC(N)c1ccccc1-c1ccc(Sc2ccc(OCCCC)cc2)c(S(=O)(=O)O)c1, CCCOc1ccccc1-c1nnc(NN)s1.Cl, COC(=O)[C@H](O[C@@H]1O[C@@H](C)[C@@H](O)[C@@H](O)[C@@H]1O)[C@@H](O[C@@H]1O[C@H](CO)[C@H](OC(=O)c2ccccc2)[C@H](O[C@H](Cc2ccccc2)C(=O)O)[C@H]1OC(=O)c1ccccc1)C(=O)OC, O=c1nc(NC2CCCC2)sc2c([N+](=O)[O-])cc(C(F)(F)F)cc12, N=C(N)NCCCOc1ccc(CNc2nc3ccc(Oc4ccc(F)cc4)cc3s2)cc1, CC(C)C[C@@H]1NC(=O)[C@H](CCCNC(N)=O)NC(=O)[C@H](CCCCN)NC(=O)[C@H](CC(=O)O)NC(=O)[C@H](CCCCN)NC(=O)CCNC1=O, , CC(O)CN1CCC(CN(C)Cc2cc(C#N)ccc2F)CC1, Nc1cccc(CNCc2ccc(-c3ccc(-c4nc5cc(C(F)(F)F)ccc5[nH]4)s3)cc2)c1, CCCCCCCNC(C1=C(O)C(=O)c2ccccc2C1=O)c1ccc([N+](=O)[O-])cc1\n$ Inchi Key                       <str> UFBLKYIDZFRLPR-UHFFFAOYSA-N, WPEWNRKLKLNLSO-UHFFFAOYSA-N, KGUJQZWYZPYYRZ-LWEWUKDVSA-N, QGDMYSDFCXOKML-UHFFFAOYSA-N, RXTJPHLPHOZLFS-UHFFFAOYSA-N, QJQNNLICZLLPMB-VUBDRERZSA-N, , FZEVYCHTADTXPM-UHFFFAOYSA-N, KZOHKPSNJBXTRJ-UHFFFAOYSA-N, AXOVDUYYBUYLPC-UHFFFAOYSA-N\n\nNone\n```\n:::\n:::\n\n\nThere were a few terms where I wasn't sure of their exact meanings, so I went through the ChEMBL_31 schema documentation and ChEMBL database website to find out. This took a while and was an important step to take so that I would know what to do when reaching the ML phase.\n\nI have selected a few physicochemical properties down below so that readers and I could gather some reasonable understandings for each term. The explanations for each term were adapted from ChEMBL_31 schema documentation (available as \"Release notes\" on the website), or if definitions for certain terms were not available from the documentation, I resorted to interpret them myself by going into \"Dinstict compounds\" section on the ChEMBL database, where I would click on, e.g. bioactivities, for a random compound in there to see what results showed up and then described them below.\n\nThe definitions for some of the listed physicochemical properties were:\n\n**Max Phase** - Maximum phase of development reached for the compound (where 4 = approved). Null was where max phase has not yet been assigned.\n\n**Bioactivities** - Various biological assays used for the compounds e.g. IC~50~, GI~50~, potency tests etc.\n\n**AlogP** - Calculated partition coefficient\n\n**HBA** - Number of hydrogen bond acceptors\n\n**HBD** - Number of hydrogen bond donors\n\n**#RO5 Violations** - Number of violations of Lipinski's rule-of-five, using HBA and HBD definitions\n\n**Passes Ro3** - Indicated whether the compound passed the rule-of-three (MW \\< 300, logP \\< 3 etc)\n\n**QED Weighted** - Weighted quantitative estimate of drug likeness (as defined by Bickerton *et al.*, Nature Chem 2012)\n\n**Inorganic flag** - Indicated whether the molecule was inorganic (i.e., containing only metal atoms and \\<2 carbon atoms), where 1 = inorganic compound and -1 = not inorganic compound (assuming 0 meant it was neither case or yet to be assigned)\n\n**Heavy Atoms** - Number of heavy (non-hydrogen) atoms\n\n**CX Acidic pKa** - The most acidic pKa calculated using ChemAxon v17.29.0\n\n**CX Basic pKa** - The most basic pKa calculated using ChemAxon v17.29.0\n\n**CX LogP** - The calculated octanol/water partition coefficient using ChemAxon v17.29.0\n\n**CX LogD** - The calculated octanol/water distribution coefficient at pH = 7.4 using ChemAxon v17.29.0\n\n**Structure Type** - based on compound_structures table, where SEQ indicated an entry in the protein_therapeutics table instead, NONE indicated an entry in neither tables, e.g. structure unknown\n\n**Inchi Key** - the IUPAC international chemical identifier key\n\nFrom the df.glimpse() method previously, there were a lot of columns with the data type of \"Utf8\", which meant they were strings. There were only two columns that had \"Int64\", which meant they were integers. A lot of these columns were actually storing numbers as strings. So to make my life easier, I went on to convert these data types into the more appropriate ones for selected columns.\n\n::: {.cell execution_count=7}\n``` {.python .cell-code}\n# Convert data types for multiple selected columns\n# Note: only takes two positional arguments, \n# so needed to use [] in code to allow more than two\n\n# Multiple columns all at once - with_columns()\n# *Single column - with_column() \n# *this only worked at the time of writing the post (around published date), \n# this is not going to work currently as Polars has been updated, \n# please use with_columns() for single or multiple columns instead*\n\n# Use alias if wanting to keep original data type in column, \n# as it adds a new column under an alias name to dataframe\ndf_new = df.with_columns(\n    [\n        (pl.col(\"Molecular Weight\")).cast(pl.Float64, strict = False),\n        (pl.col(\"Targets\")).cast(pl.Int64, strict = False),\n        (pl.col(\"Bioactivities\")).cast(pl.Int64, strict = False),\n        (pl.col(\"AlogP\")).cast(pl.Float64, strict = False),\n        (pl.col(\"Polar Surface Area\")).cast(pl.Float64, strict = False),\n        (pl.col(\"HBA\")).cast(pl.Int64, strict = False),\n        (pl.col(\"HBD\")).cast(pl.Int64, strict = False),\n        (pl.col(\"#RO5 Violations\")).cast(pl.Int64, strict = False),\n        (pl.col(\"#Rotatable Bonds\")).cast(pl.Int64, strict = False),\n        (pl.col(\"QED Weighted\")).cast(pl.Float64, strict = False),\n        (pl.col(\"CX Acidic pKa\")).cast(pl.Float64, strict = False),\n        (pl.col(\"CX Basic pKa\")).cast(pl.Float64, strict = False),\n        (pl.col(\"CX LogP\")).cast(pl.Float64, strict = False),\n        (pl.col(\"CX LogD\")).cast(pl.Float64, strict = False),\n        (pl.col(\"Aromatic Rings\")).cast(pl.Int64, strict = False),\n        (pl.col(\"Heavy Atoms\")).cast(pl.Int64, strict = False),\n        (pl.col(\"HBA (Lipinski)\")).cast(pl.Int64, strict = False),\n        (pl.col(\"HBD (Lipinski)\")).cast(pl.Int64, strict = False),\n        (pl.col(\"#RO5 Violations (Lipinski)\")).cast(pl.Int64, strict = False),\n        (pl.col(\"Molecular Weight (Monoisotopic)\")).cast(pl.Float64, strict = False)\n    ]\n)\ndf_new.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=53}\n```{=html}\n<div><style>\n.dataframe > thead > tr > th,\n.dataframe > tbody > tr > td {\n  text-align: right;\n}\n</style>\n<small>shape: (5, 32)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>ChEMBL ID</th><th>Name</th><th>Synonyms</th><th>Type</th><th>Max Phase</th><th>Molecular Weight</th><th>Targets</th><th>Bioactivities</th><th>AlogP</th><th>Polar Surface Area</th><th>HBA</th><th>HBD</th><th>#RO5 Violations</th><th>#Rotatable Bonds</th><th>Passes Ro3</th><th>QED Weighted</th><th>CX Acidic pKa</th><th>CX Basic pKa</th><th>CX LogP</th><th>CX LogD</th><th>Aromatic Rings</th><th>Structure Type</th><th>Inorganic Flag</th><th>Heavy Atoms</th><th>HBA (Lipinski)</th><th>HBD (Lipinski)</th><th>#RO5 Violations (Lipinski)</th><th>Molecular Weight (Monoisotopic)</th><th>Molecular Species</th><th>Molecular Formula</th><th>Smiles</th><th>Inchi Key</th></tr><tr><td>str</td><td>str</td><td>str</td><td>str</td><td>i64</td><td>f64</td><td>i64</td><td>i64</td><td>f64</td><td>f64</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>str</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>i64</td><td>str</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>f64</td><td>str</td><td>str</td><td>str</td><td>str</td></tr></thead><tbody><tr><td>&quot;CHEMBL1206185&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>607.88</td><td>null</td><td>null</td><td>9.46</td><td>89.62</td><td>5</td><td>2</td><td>2</td><td>17</td><td>&quot;N&quot;</td><td>0.09</td><td>-1.91</td><td>8.38</td><td>9.4</td><td>9.36</td><td>3</td><td>&quot;MOL&quot;</td><td>-1</td><td>42</td><td>5</td><td>3</td><td>2</td><td>607.279</td><td>&quot;ACID&quot;</td><td>&quot;C35H45NO4S2&quot;</td><td>&quot;CCCCCCCCCCC#CC…</td><td>&quot;UFBLKYIDZFRLPR…</td></tr><tr><td>&quot;CHEMBL539070&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>286.79</td><td>1</td><td>1</td><td>2.28</td><td>73.06</td><td>6</td><td>2</td><td>0</td><td>5</td><td>&quot;N&quot;</td><td>0.63</td><td>13.84</td><td>3.64</td><td>2.57</td><td>2.57</td><td>2</td><td>&quot;MOL&quot;</td><td>-1</td><td>17</td><td>5</td><td>3</td><td>0</td><td>250.0888</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C11H15ClN4OS&quot;</td><td>&quot;CCCOc1ccccc1-c…</td><td>&quot;WPEWNRKLKLNLSO…</td></tr><tr><td>&quot;CHEMBL3335528&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>842.8</td><td>2</td><td>6</td><td>0.18</td><td>269.57</td><td>18</td><td>5</td><td>2</td><td>17</td><td>&quot;N&quot;</td><td>0.09</td><td>3.2</td><td>null</td><td>3.31</td><td>-0.14</td><td>3</td><td>&quot;MOL&quot;</td><td>-1</td><td>60</td><td>19</td><td>5</td><td>2</td><td>842.2633</td><td>&quot;ACID&quot;</td><td>&quot;C41H46O19&quot;</td><td>&quot;COC(=O)[C@H](O…</td><td>&quot;KGUJQZWYZPYYRZ…</td></tr><tr><td>&quot;CHEMBL2419030&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>359.33</td><td>4</td><td>4</td><td>3.94</td><td>85.13</td><td>6</td><td>1</td><td>0</td><td>3</td><td>&quot;N&quot;</td><td>0.66</td><td>null</td><td>null</td><td>3.66</td><td>3.66</td><td>2</td><td>&quot;MOL&quot;</td><td>-1</td><td>24</td><td>6</td><td>1</td><td>0</td><td>359.0551</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C14H12F3N3O3S&quot;</td><td>&quot;O=c1nc(NC2CCCC…</td><td>&quot;QGDMYSDFCXOKML…</td></tr><tr><td>&quot;CHEMBL4301448&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>465.55</td><td>null</td><td>null</td><td>5.09</td><td>105.28</td><td>6</td><td>4</td><td>1</td><td>10</td><td>&quot;N&quot;</td><td>0.15</td><td>null</td><td>12.14</td><td>4.41</td><td>2.0</td><td>4</td><td>&quot;MOL&quot;</td><td>-1</td><td>33</td><td>7</td><td>5</td><td>1</td><td>465.1635</td><td>&quot;BASE&quot;</td><td>&quot;C24H24FN5O2S&quot;</td><td>&quot;N=C(N)NCCCOc1c…</td><td>&quot;RXTJPHLPHOZLFS…</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\nOnce all the columns' data types have been checked and converted to appropriate types accordingly, I used null_count() to see the distributions of all null entries in the dataset.\n\n::: {.cell execution_count=8}\n``` {.python .cell-code}\n# Check for any null or NA or \"\" entries in the dataset\n# Alternative code that worked similarly was df.select(pl.all().null_count())\ndf_new.null_count()\n```\n\n::: {.cell-output .cell-output-display execution_count=54}\n```{=html}\n<div><style>\n.dataframe > thead > tr > th,\n.dataframe > tbody > tr > td {\n  text-align: right;\n}\n</style>\n<small>shape: (1, 32)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>ChEMBL ID</th><th>Name</th><th>Synonyms</th><th>Type</th><th>Max Phase</th><th>Molecular Weight</th><th>Targets</th><th>Bioactivities</th><th>AlogP</th><th>Polar Surface Area</th><th>HBA</th><th>HBD</th><th>#RO5 Violations</th><th>#Rotatable Bonds</th><th>Passes Ro3</th><th>QED Weighted</th><th>CX Acidic pKa</th><th>CX Basic pKa</th><th>CX LogP</th><th>CX LogD</th><th>Aromatic Rings</th><th>Structure Type</th><th>Inorganic Flag</th><th>Heavy Atoms</th><th>HBA (Lipinski)</th><th>HBD (Lipinski)</th><th>#RO5 Violations (Lipinski)</th><th>Molecular Weight (Monoisotopic)</th><th>Molecular Species</th><th>Molecular Formula</th><th>Smiles</th><th>Inchi Key</th></tr><tr><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td></tr></thead><tbody><tr><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>23249</td><td>96223</td><td>96223</td><td>83571</td><td>83571</td><td>83571</td><td>83571</td><td>83571</td><td>83571</td><td>0</td><td>83571</td><td>1052439</td><td>882168</td><td>83795</td><td>83795</td><td>83571</td><td>0</td><td>0</td><td>83571</td><td>83571</td><td>83571</td><td>83571</td><td>23252</td><td>0</td><td>0</td><td>0</td><td>0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n::: {.cell execution_count=9}\n``` {.python .cell-code}\n# Drop rows with null entries\ndf_dn = df_new.drop_nulls()\ndf_dn \n# Number of rows reduced to 736,570\n```\n\n::: {.cell-output .cell-output-display execution_count=55}\n```{=html}\n<div><style>\n.dataframe > thead > tr > th,\n.dataframe > tbody > tr > td {\n  text-align: right;\n}\n</style>\n<small>shape: (736_570, 32)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>ChEMBL ID</th><th>Name</th><th>Synonyms</th><th>Type</th><th>Max Phase</th><th>Molecular Weight</th><th>Targets</th><th>Bioactivities</th><th>AlogP</th><th>Polar Surface Area</th><th>HBA</th><th>HBD</th><th>#RO5 Violations</th><th>#Rotatable Bonds</th><th>Passes Ro3</th><th>QED Weighted</th><th>CX Acidic pKa</th><th>CX Basic pKa</th><th>CX LogP</th><th>CX LogD</th><th>Aromatic Rings</th><th>Structure Type</th><th>Inorganic Flag</th><th>Heavy Atoms</th><th>HBA (Lipinski)</th><th>HBD (Lipinski)</th><th>#RO5 Violations (Lipinski)</th><th>Molecular Weight (Monoisotopic)</th><th>Molecular Species</th><th>Molecular Formula</th><th>Smiles</th><th>Inchi Key</th></tr><tr><td>str</td><td>str</td><td>str</td><td>str</td><td>i64</td><td>f64</td><td>i64</td><td>i64</td><td>f64</td><td>f64</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>str</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>i64</td><td>str</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>f64</td><td>str</td><td>str</td><td>str</td><td>str</td></tr></thead><tbody><tr><td>&quot;CHEMBL539070&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>286.79</td><td>1</td><td>1</td><td>2.28</td><td>73.06</td><td>6</td><td>2</td><td>0</td><td>5</td><td>&quot;N&quot;</td><td>0.63</td><td>13.84</td><td>3.64</td><td>2.57</td><td>2.57</td><td>2</td><td>&quot;MOL&quot;</td><td>-1</td><td>17</td><td>5</td><td>3</td><td>0</td><td>250.0888</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C11H15ClN4OS&quot;</td><td>&quot;CCCOc1ccccc1-c…</td><td>&quot;WPEWNRKLKLNLSO…</td></tr><tr><td>&quot;CHEMBL3827271&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>712.85</td><td>1</td><td>1</td><td>-2.84</td><td>319.06</td><td>10</td><td>11</td><td>2</td><td>16</td><td>&quot;N&quot;</td><td>0.07</td><td>4.08</td><td>10.49</td><td>-6.88</td><td>-8.95</td><td>0</td><td>&quot;MOL&quot;</td><td>-1</td><td>50</td><td>19</td><td>14</td><td>3</td><td>712.4232</td><td>&quot;ZWITTERION&quot;</td><td>&quot;C31H56N10O9&quot;</td><td>&quot;CC(C)C[C@@H]1N…</td><td>&quot;QJQNNLICZLLPMB…</td></tr><tr><td>&quot;CHEMBL3824158&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>422.48</td><td>2</td><td>4</td><td>5.09</td><td>109.54</td><td>6</td><td>2</td><td>1</td><td>10</td><td>&quot;N&quot;</td><td>0.31</td><td>4.59</td><td>7.99</td><td>2.49</td><td>2.42</td><td>2</td><td>&quot;MOL&quot;</td><td>-1</td><td>31</td><td>7</td><td>2</td><td>1</td><td>422.1842</td><td>&quot;ACID&quot;</td><td>&quot;C24H26N2O5&quot;</td><td>&quot;CCCCCCCNC(C1=C…</td><td>&quot;AXOVDUYYBUYLPC…</td></tr><tr><td>&quot;CHEMBL1991010&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>454.05</td><td>60</td><td>60</td><td>5.18</td><td>40.54</td><td>3</td><td>1</td><td>1</td><td>8</td><td>&quot;N&quot;</td><td>0.6</td><td>13.88</td><td>8.48</td><td>6.34</td><td>5.22</td><td>2</td><td>&quot;MOL&quot;</td><td>-1</td><td>31</td><td>3</td><td>1</td><td>1</td><td>417.2668</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C28H36ClNO2&quot;</td><td>&quot;CCc1ccc(/C=C/C…</td><td>&quot;XJDPAUYFONOZBC…</td></tr><tr><td>&quot;CHEMBL195644&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>375.47</td><td>2</td><td>3</td><td>4.95</td><td>70.42</td><td>4</td><td>2</td><td>0</td><td>2</td><td>&quot;N&quot;</td><td>0.73</td><td>9.52</td><td>3.73</td><td>3.92</td><td>3.91</td><td>2</td><td>&quot;MOL&quot;</td><td>-1</td><td>28</td><td>4</td><td>2</td><td>0</td><td>375.1834</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C24H25NO3&quot;</td><td>&quot;C[C@]12CCC3c4c…</td><td>&quot;MOBPUUUBXAHZBM…</td></tr><tr><td>&quot;CHEMBL255263&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>388.42</td><td>4</td><td>4</td><td>2.42</td><td>95.16</td><td>4</td><td>2</td><td>0</td><td>4</td><td>&quot;N&quot;</td><td>0.72</td><td>11.24</td><td>1.02</td><td>1.74</td><td>1.74</td><td>3</td><td>&quot;MOL&quot;</td><td>-1</td><td>27</td><td>7</td><td>2</td><td>0</td><td>388.1005</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C18H17FN4O3S&quot;</td><td>&quot;O=C(Cc1ccc(F)c…</td><td>&quot;JXSGQHRSUUOSAF…</td></tr><tr><td>&quot;CHEMBL504846&quot;</td><td>&quot;&quot;</td><td>&quot;25-Deacetyl-Ri…</td><td>&quot;Small molecule…</td><td>0</td><td>807.0</td><td>3</td><td>21</td><td>3.9</td><td>202.64</td><td>13</td><td>7</td><td>3</td><td>3</td><td>&quot;N&quot;</td><td>0.23</td><td>8.61</td><td>8.27</td><td>3.4</td><td>2.87</td><td>1</td><td>&quot;MOL&quot;</td><td>-1</td><td>58</td><td>14</td><td>7</td><td>3</td><td>806.4466</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C44H62N4O10&quot;</td><td>&quot;CO[C@H]1/C=C/O…</td><td>&quot;MVUYPJALSSDCQB…</td></tr><tr><td>&quot;CHEMBL85010&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>508.96</td><td>4</td><td>5</td><td>2.65</td><td>139.21</td><td>9</td><td>3</td><td>1</td><td>7</td><td>&quot;N&quot;</td><td>0.22</td><td>7.03</td><td>2.71</td><td>3.27</td><td>2.75</td><td>1</td><td>&quot;MOL&quot;</td><td>-1</td><td>35</td><td>10</td><td>3</td><td>1</td><td>508.1612</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C24H29ClN2O8&quot;</td><td>&quot;CCOCCNC(=O)CO/…</td><td>&quot;PHPBXALSGRFDIK…</td></tr><tr><td>&quot;CHEMBL1364151&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>314.39</td><td>5</td><td>6</td><td>2.5</td><td>54.56</td><td>4</td><td>1</td><td>0</td><td>3</td><td>&quot;N&quot;</td><td>0.88</td><td>13.45</td><td>7.28</td><td>2.38</td><td>2.14</td><td>2</td><td>&quot;MOL&quot;</td><td>-1</td><td>23</td><td>5</td><td>1</td><td>0</td><td>314.163</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C18H22N2O3&quot;</td><td>&quot;Cc1[nH]c2ccccc…</td><td>&quot;OKIWVYPITFJCJI…</td></tr><tr><td>&quot;CHEMBL2047203&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>855.36</td><td>5</td><td>6</td><td>7.45</td><td>272.16</td><td>10</td><td>4</td><td>2</td><td>13</td><td>&quot;N&quot;</td><td>0.06</td><td>-10.58</td><td>5.78</td><td>4.35</td><td>4.11</td><td>4</td><td>&quot;MOL&quot;</td><td>-1</td><td>61</td><td>20</td><td>4</td><td>3</td><td>854.3492</td><td>&quot;ACID&quot;</td><td>&quot;C40H47ClN14O6&quot;</td><td>&quot;COC(=O)N[C@H](…</td><td>&quot;QDXJQBSKIKHCKU…</td></tr><tr><td>&quot;CHEMBL3798157&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>455.45</td><td>28</td><td>64</td><td>4.77</td><td>105.24</td><td>6</td><td>3</td><td>0</td><td>5</td><td>&quot;N&quot;</td><td>0.4</td><td>7.29</td><td>3.02</td><td>3.97</td><td>3.64</td><td>4</td><td>&quot;MOL&quot;</td><td>-1</td><td>32</td><td>8</td><td>3</td><td>0</td><td>455.0864</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C21H15F2N5O3S&quot;</td><td>&quot;CNC(=O)c1cc(Oc…</td><td>&quot;LADWERPDOVRXBZ…</td></tr><tr><td>&quot;CHEMBL1337107&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>296.33</td><td>2</td><td>2</td><td>2.29</td><td>64.35</td><td>5</td><td>1</td><td>0</td><td>4</td><td>&quot;N&quot;</td><td>0.75</td><td>12.82</td><td>4.35</td><td>2.35</td><td>2.35</td><td>3</td><td>&quot;MOL&quot;</td><td>-1</td><td>22</td><td>5</td><td>1</td><td>0</td><td>296.1161</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C17H16N2O3&quot;</td><td>&quot;COC(=O)Cn1c(C(…</td><td>&quot;SBCXFZQMSVPTPA…</td></tr><tr><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td></tr><tr><td>&quot;CHEMBL255122&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>529.07</td><td>1</td><td>2</td><td>2.81</td><td>110.43</td><td>6</td><td>3</td><td>1</td><td>5</td><td>&quot;N&quot;</td><td>0.47</td><td>12.29</td><td>6.33</td><td>1.68</td><td>1.65</td><td>3</td><td>&quot;MOL&quot;</td><td>-1</td><td>36</td><td>9</td><td>3</td><td>1</td><td>528.171</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C25H29ClN6O3S&quot;</td><td>&quot;CCC(=O)N1CCC(N…</td><td>&quot;RAMXCQDJYLSGRA…</td></tr><tr><td>&quot;CHEMBL2018776&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>516.04</td><td>5</td><td>5</td><td>6.1</td><td>97.84</td><td>8</td><td>2</td><td>2</td><td>13</td><td>&quot;N&quot;</td><td>0.26</td><td>12.76</td><td>9.18</td><td>5.66</td><td>3.88</td><td>3</td><td>&quot;MOL&quot;</td><td>-1</td><td>36</td><td>9</td><td>2</td><td>2</td><td>515.2299</td><td>&quot;BASE&quot;</td><td>&quot;C26H34ClN5O4&quot;</td><td>&quot;CCCCOc1cc2c(Nc…</td><td>&quot;FARPVPMCEBTTDI…</td></tr><tr><td>&quot;CHEMBL97207&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>286.12</td><td>2</td><td>2</td><td>1.31</td><td>99.82</td><td>5</td><td>2</td><td>0</td><td>3</td><td>&quot;N&quot;</td><td>0.89</td><td>13.08</td><td>0.38</td><td>2.1</td><td>2.1</td><td>2</td><td>&quot;MOL&quot;</td><td>-1</td><td>18</td><td>6</td><td>4</td><td>0</td><td>285.0184</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C10H9Cl2N5O&quot;</td><td>&quot;NC(=O)c1nnn(Cc…</td><td>&quot;HULYRQSWFVUVSF…</td></tr><tr><td>&quot;CHEMBL221343&quot;</td><td>&quot;&quot;</td><td>&quot;LUF-5980&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>313.4</td><td>5</td><td>7</td><td>5.42</td><td>41.57</td><td>2</td><td>1</td><td>1</td><td>3</td><td>&quot;N&quot;</td><td>0.55</td><td>11.75</td><td>3.12</td><td>5.46</td><td>5.46</td><td>4</td><td>&quot;MOL&quot;</td><td>-1</td><td>24</td><td>3</td><td>1</td><td>1</td><td>313.1579</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C21H19N3&quot;</td><td>&quot;CC(C)c1nc2c(-c…</td><td>&quot;REXYMDQLBZWOMA…</td></tr><tr><td>&quot;CHEMBL1420018&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>255.27</td><td>15</td><td>20</td><td>2.31</td><td>69.39</td><td>4</td><td>1</td><td>0</td><td>4</td><td>&quot;N&quot;</td><td>0.52</td><td>13.72</td><td>2.76</td><td>2.38</td><td>2.38</td><td>2</td><td>&quot;MOL&quot;</td><td>-1</td><td>19</td><td>4</td><td>2</td><td>0</td><td>255.0895</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C15H13NO3&quot;</td><td>&quot;Nc1cccc(C(=O)O…</td><td>&quot;UTIDKUVFKVXYLT…</td></tr><tr><td>&quot;CHEMBL2314244&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>470.61</td><td>7</td><td>9</td><td>1.86</td><td>122.72</td><td>6</td><td>6</td><td>1</td><td>17</td><td>&quot;N&quot;</td><td>0.2</td><td>8.96</td><td>10.81</td><td>-0.72</td><td>-3.93</td><td>2</td><td>&quot;MOL&quot;</td><td>-1</td><td>34</td><td>8</td><td>6</td><td>1</td><td>470.2893</td><td>&quot;BASE&quot;</td><td>&quot;C26H38N4O4&quot;</td><td>&quot;O=C(Cc1ccccc1O…</td><td>&quot;SUKXUTUXGGJIBX…</td></tr><tr><td>&quot;CHEMBL1420130&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>226.3</td><td>2</td><td>2</td><td>1.89</td><td>63.08</td><td>5</td><td>1</td><td>0</td><td>3</td><td>&quot;N&quot;</td><td>0.63</td><td>12.05</td><td>1.31</td><td>2.94</td><td>2.94</td><td>1</td><td>&quot;MOL&quot;</td><td>-1</td><td>15</td><td>4</td><td>1</td><td>0</td><td>226.0776</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C10H14N2O2S&quot;</td><td>&quot;CC(C)(C)C(=O)C…</td><td>&quot;LCGAKQAOOABKRG…</td></tr><tr><td>&quot;CHEMBL2419480&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>456.52</td><td>3</td><td>3</td><td>1.56</td><td>129.46</td><td>8</td><td>1</td><td>0</td><td>8</td><td>&quot;N&quot;</td><td>0.59</td><td>3.99</td><td>1.9</td><td>2.14</td><td>1.2</td><td>2</td><td>&quot;MOL&quot;</td><td>-1</td><td>32</td><td>9</td><td>1</td><td>0</td><td>456.1467</td><td>&quot;ACID&quot;</td><td>&quot;C22H24N4O5S&quot;</td><td>&quot;CCOC(=O)c1cc(C…</td><td>&quot;TXYSLOQUANFYQS…</td></tr><tr><td>&quot;CHEMBL540121&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>540.05</td><td>2</td><td>3</td><td>2.39</td><td>147.14</td><td>6</td><td>4</td><td>1</td><td>8</td><td>&quot;N&quot;</td><td>0.22</td><td>5.02</td><td>11.48</td><td>-0.75</td><td>-0.78</td><td>4</td><td>&quot;MOL&quot;</td><td>-1</td><td>36</td><td>9</td><td>5</td><td>1</td><td>503.1627</td><td>&quot;ZWITTERION&quot;</td><td>&quot;C26H26ClN5O4S&quot;</td><td>&quot;Cc1ccn(NS(=O)(…</td><td>&quot;TZLGWENJAJXWGA…</td></tr><tr><td>&quot;CHEMBL374041&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>504.5</td><td>2</td><td>4</td><td>3.04</td><td>144.95</td><td>8</td><td>3</td><td>1</td><td>10</td><td>&quot;N&quot;</td><td>0.28</td><td>6.59</td><td>4.37</td><td>2.17</td><td>1.33</td><td>3</td><td>&quot;MOL&quot;</td><td>-1</td><td>37</td><td>11</td><td>3</td><td>2</td><td>504.1645</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C26H24N4O7&quot;</td><td>&quot;CCOCCC1(Oc2ccc…</td><td>&quot;ABCSNHDQYHOLOO…</td></tr><tr><td>&quot;CHEMBL2017916&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>312.35</td><td>3</td><td>3</td><td>2.86</td><td>77.0</td><td>6</td><td>1</td><td>0</td><td>4</td><td>&quot;N&quot;</td><td>0.8</td><td>8.13</td><td>3.49</td><td>2.17</td><td>2.1</td><td>3</td><td>&quot;MOL&quot;</td><td>-1</td><td>22</td><td>6</td><td>1</td><td>0</td><td>312.0681</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C15H12N4O2S&quot;</td><td>&quot;COc1ccc(-c2nnc…</td><td>&quot;XIZUJGDKNPVNQA…</td></tr><tr><td>&quot;CHEMBL1416264&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>380.41</td><td>6</td><td>8</td><td>3.06</td><td>85.07</td><td>7</td><td>1</td><td>0</td><td>5</td><td>&quot;N&quot;</td><td>0.54</td><td>13.85</td><td>3.86</td><td>2.47</td><td>2.47</td><td>4</td><td>&quot;MOL&quot;</td><td>-1</td><td>27</td><td>7</td><td>1</td><td>0</td><td>380.0856</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C18H13FN6OS&quot;</td><td>&quot;O=C(CSc1ccc2nn…</td><td>&quot;QVYIEKHEJKFNAT…</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n::: {.cell execution_count=10}\n``` {.python .cell-code}\n# Check that all rows with null values were dropped\ndf_dn.null_count()\n```\n\n::: {.cell-output .cell-output-display execution_count=56}\n```{=html}\n<div><style>\n.dataframe > thead > tr > th,\n.dataframe > tbody > tr > td {\n  text-align: right;\n}\n</style>\n<small>shape: (1, 32)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>ChEMBL ID</th><th>Name</th><th>Synonyms</th><th>Type</th><th>Max Phase</th><th>Molecular Weight</th><th>Targets</th><th>Bioactivities</th><th>AlogP</th><th>Polar Surface Area</th><th>HBA</th><th>HBD</th><th>#RO5 Violations</th><th>#Rotatable Bonds</th><th>Passes Ro3</th><th>QED Weighted</th><th>CX Acidic pKa</th><th>CX Basic pKa</th><th>CX LogP</th><th>CX LogD</th><th>Aromatic Rings</th><th>Structure Type</th><th>Inorganic Flag</th><th>Heavy Atoms</th><th>HBA (Lipinski)</th><th>HBD (Lipinski)</th><th>#RO5 Violations (Lipinski)</th><th>Molecular Weight (Monoisotopic)</th><th>Molecular Species</th><th>Molecular Formula</th><th>Smiles</th><th>Inchi Key</th></tr><tr><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td></tr></thead><tbody><tr><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n::: {.cell execution_count=11}\n``` {.python .cell-code}\n# To see summary statistics for df_dn dataset\ndf_dn.describe()\n```\n\n::: {.cell-output .cell-output-display execution_count=57}\n```{=html}\n<div><style>\n.dataframe > thead > tr > th,\n.dataframe > tbody > tr > td {\n  text-align: right;\n}\n</style>\n<small>shape: (9, 33)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>describe</th><th>ChEMBL ID</th><th>Name</th><th>Synonyms</th><th>Type</th><th>Max Phase</th><th>Molecular Weight</th><th>Targets</th><th>Bioactivities</th><th>AlogP</th><th>Polar Surface Area</th><th>HBA</th><th>HBD</th><th>#RO5 Violations</th><th>#Rotatable Bonds</th><th>Passes Ro3</th><th>QED Weighted</th><th>CX Acidic pKa</th><th>CX Basic pKa</th><th>CX LogP</th><th>CX LogD</th><th>Aromatic Rings</th><th>Structure Type</th><th>Inorganic Flag</th><th>Heavy Atoms</th><th>HBA (Lipinski)</th><th>HBD (Lipinski)</th><th>#RO5 Violations (Lipinski)</th><th>Molecular Weight (Monoisotopic)</th><th>Molecular Species</th><th>Molecular Formula</th><th>Smiles</th><th>Inchi Key</th></tr><tr><td>str</td><td>str</td><td>str</td><td>str</td><td>str</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>str</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>str</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>str</td><td>str</td><td>str</td><td>str</td></tr></thead><tbody><tr><td>&quot;count&quot;</td><td>&quot;736570&quot;</td><td>&quot;736570&quot;</td><td>&quot;736570&quot;</td><td>&quot;736570&quot;</td><td>736570.0</td><td>736570.0</td><td>736570.0</td><td>736570.0</td><td>736570.0</td><td>736570.0</td><td>736570.0</td><td>736570.0</td><td>736570.0</td><td>736570.0</td><td>&quot;736570&quot;</td><td>736570.0</td><td>736570.0</td><td>736570.0</td><td>736570.0</td><td>736570.0</td><td>736570.0</td><td>&quot;736570&quot;</td><td>736570.0</td><td>736570.0</td><td>736570.0</td><td>736570.0</td><td>736570.0</td><td>736570.0</td><td>&quot;736570&quot;</td><td>&quot;736570&quot;</td><td>&quot;736570&quot;</td><td>&quot;736570&quot;</td></tr><tr><td>&quot;null_count&quot;</td><td>&quot;0&quot;</td><td>&quot;0&quot;</td><td>&quot;0&quot;</td><td>&quot;0&quot;</td><td>0.0</td><td>0.0</td><td>0.0</td><td>0.0</td><td>0.0</td><td>0.0</td><td>0.0</td><td>0.0</td><td>0.0</td><td>0.0</td><td>&quot;0&quot;</td><td>0.0</td><td>0.0</td><td>0.0</td><td>0.0</td><td>0.0</td><td>0.0</td><td>&quot;0&quot;</td><td>0.0</td><td>0.0</td><td>0.0</td><td>0.0</td><td>0.0</td><td>0.0</td><td>&quot;0&quot;</td><td>&quot;0&quot;</td><td>&quot;0&quot;</td><td>&quot;0&quot;</td></tr><tr><td>&quot;mean&quot;</td><td>null</td><td>null</td><td>null</td><td>null</td><td>0.007937</td><td>431.880042</td><td>5.520715</td><td>8.705471</td><td>3.325204</td><td>97.58116</td><td>5.890221</td><td>2.274721</td><td>0.489124</td><td>6.216262</td><td>null</td><td>0.510936</td><td>9.59944</td><td>5.074377</td><td>2.815115</td><td>2.17363</td><td>2.754412</td><td>null</td><td>-0.929521</td><td>30.266113</td><td>7.276555</td><td>2.497847</td><td>0.576319</td><td>428.334452</td><td>null</td><td>null</td><td>null</td><td>null</td></tr><tr><td>&quot;std&quot;</td><td>null</td><td>null</td><td>null</td><td>null</td><td>0.164565</td><td>135.637543</td><td>14.784793</td><td>55.537836</td><td>1.980414</td><td>47.40847</td><td>2.459106</td><td>1.681943</td><td>0.794171</td><td>3.894505</td><td>null</td><td>0.229039</td><td>3.583639</td><td>3.234099</td><td>2.286325</td><td>2.645694</td><td>1.2009</td><td>null</td><td>0.255953</td><td>9.54406</td><td>3.067158</td><td>2.081485</td><td>0.908719</td><td>133.755653</td><td>null</td><td>null</td><td>null</td><td>null</td></tr><tr><td>&quot;min&quot;</td><td>&quot;CHEMBL10&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>&quot;&quot;</td><td>0.0</td><td>45.04</td><td>1.0</td><td>1.0</td><td>-12.92</td><td>3.24</td><td>1.0</td><td>0.0</td><td>0.0</td><td>0.0</td><td>&quot;N&quot;</td><td>0.01</td><td>-20.03</td><td>0.0</td><td>-16.71</td><td>-26.04</td><td>0.0</td><td>&quot;BOTH&quot;</td><td>-1.0</td><td>3.0</td><td>1.0</td><td>0.0</td><td>0.0</td><td>45.0215</td><td>&quot;ACID&quot;</td><td>&quot;C10H10Br2N2O&quot;</td><td>&quot;Br.Br.C/C(=N/N…</td><td>&quot;AAAADVYFXUUVEO…</td></tr><tr><td>&quot;max&quot;</td><td>&quot;CHEMBL99998&quot;</td><td>&quot;t-4-AMINOCROTO…</td><td>&quot;trovafloxacin9…</td><td>&quot;Unknown&quot;</td><td>4.0</td><td>1901.51</td><td>1334.0</td><td>17911.0</td><td>16.83</td><td>595.22</td><td>32.0</td><td>25.0</td><td>4.0</td><td>59.0</td><td>&quot;Y&quot;</td><td>0.95</td><td>14.0</td><td>38.8</td><td>18.31</td><td>18.31</td><td>28.0</td><td>&quot;MOL&quot;</td><td>0.0</td><td>76.0</td><td>34.0</td><td>32.0</td><td>4.0</td><td>999.4063</td><td>&quot;ZWITTERION&quot;</td><td>&quot;HNNa2O8S2&quot;</td><td>&quot;n1nc2c([nH]1)c…</td><td>&quot;ZZZZEJJXQQRZBH…</td></tr><tr><td>&quot;median&quot;</td><td>null</td><td>null</td><td>null</td><td>null</td><td>0.0</td><td>413.46</td><td>2.0</td><td>3.0</td><td>3.37</td><td>88.32</td><td>5.0</td><td>2.0</td><td>0.0</td><td>5.0</td><td>null</td><td>0.51</td><td>10.51</td><td>4.7</td><td>2.97</td><td>2.46</td><td>3.0</td><td>null</td><td>-1.0</td><td>29.0</td><td>7.0</td><td>2.0</td><td>0.0</td><td>410.2066</td><td>null</td><td>null</td><td>null</td><td>null</td></tr><tr><td>&quot;25%&quot;</td><td>null</td><td>null</td><td>null</td><td>null</td><td>0.0</td><td>340.47</td><td>1.0</td><td>2.0</td><td>2.21</td><td>68.29</td><td>4.0</td><td>1.0</td><td>0.0</td><td>4.0</td><td>null</td><td>0.34</td><td>7.69</td><td>2.25</td><td>1.64</td><td>0.97</td><td>2.0</td><td>null</td><td>-1.0</td><td>24.0</td><td>5.0</td><td>1.0</td><td>0.0</td><td>339.0582</td><td>null</td><td>null</td><td>null</td><td>null</td></tr><tr><td>&quot;75%&quot;</td><td>null</td><td>null</td><td>null</td><td>null</td><td>0.0</td><td>494.57</td><td>5.0</td><td>8.0</td><td>4.53</td><td>113.23</td><td>7.0</td><td>3.0</td><td>1.0</td><td>8.0</td><td>null</td><td>0.7</td><td>12.45</td><td>7.85</td><td>4.23</td><td>3.79</td><td>4.0</td><td>null</td><td>-1.0</td><td>35.0</td><td>9.0</td><td>3.0</td><td>1.0</td><td>491.0028</td><td>null</td><td>null</td><td>null</td><td>null</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n<br>\n\n##### **Some exploratory data analysis**\n\nOne of the columns that jumped out from the summary statistics of the df_dn dataset was the \"Targets\" column. It ranged from 1 to 1334 targets. Out of curiosity, I went through several places on ChEMBL website to find out the exact definition of \"Target\". Eventually I settled on an answer which explained that the \"Target\" column represented the number of targets associated with the particular ChEMBL compound listed. I then singled out the ChEMBL compound with 1334 targets recorded, it turned out to be imatinib, which was marketed as Gleevec, and was a well-known prescription medicine for leukaemia and other selected oncological disorders with many well-documented drug interactions.\n\n::: {.cell execution_count=12}\n``` {.python .cell-code}\n# This was confirmed via a filter function, which brought up CHEMBL1421, or also known as dasatinib\ndf_dn.filter(pl.col(\"Targets\") == 1334)\n```\n\n::: {.cell-output .cell-output-display execution_count=58}\n```{=html}\n<div><style>\n.dataframe > thead > tr > th,\n.dataframe > tbody > tr > td {\n  text-align: right;\n}\n</style>\n<small>shape: (1, 32)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>ChEMBL ID</th><th>Name</th><th>Synonyms</th><th>Type</th><th>Max Phase</th><th>Molecular Weight</th><th>Targets</th><th>Bioactivities</th><th>AlogP</th><th>Polar Surface Area</th><th>HBA</th><th>HBD</th><th>#RO5 Violations</th><th>#Rotatable Bonds</th><th>Passes Ro3</th><th>QED Weighted</th><th>CX Acidic pKa</th><th>CX Basic pKa</th><th>CX LogP</th><th>CX LogD</th><th>Aromatic Rings</th><th>Structure Type</th><th>Inorganic Flag</th><th>Heavy Atoms</th><th>HBA (Lipinski)</th><th>HBD (Lipinski)</th><th>#RO5 Violations (Lipinski)</th><th>Molecular Weight (Monoisotopic)</th><th>Molecular Species</th><th>Molecular Formula</th><th>Smiles</th><th>Inchi Key</th></tr><tr><td>str</td><td>str</td><td>str</td><td>str</td><td>i64</td><td>f64</td><td>i64</td><td>i64</td><td>f64</td><td>f64</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>str</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>i64</td><td>str</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>f64</td><td>str</td><td>str</td><td>str</td><td>str</td></tr></thead><tbody><tr><td>&quot;CHEMBL941&quot;</td><td>&quot;IMATINIB&quot;</td><td>&quot;GLAMOX|Gleevec…</td><td>&quot;Small molecule…</td><td>4</td><td>493.62</td><td>1334</td><td>4359</td><td>4.59</td><td>86.28</td><td>7</td><td>2</td><td>0</td><td>7</td><td>&quot;N&quot;</td><td>0.39</td><td>12.69</td><td>7.84</td><td>4.38</td><td>3.8</td><td>4</td><td>&quot;MOL&quot;</td><td>0</td><td>37</td><td>8</td><td>2</td><td>0</td><td>493.259</td><td>&quot;NEUTRAL&quot;</td><td>&quot;C29H31N7O&quot;</td><td>&quot;Cc1ccc(NC(=O)c…</td><td>&quot;KTUFNOKKBVMGRW…</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\nTo explore other physicochemical and molecular properties in the dataframe, \"Max Phase\" was one of the first few that drew my interests. So it tagged each ChEMBL compound with a max phase number from 0 to 4, where 4 meant the compound was approved (usually also meant it was already a prescription medicine). Thinking along this line, I thought what about those compounds that had max phase as 0, because they were the ones still pending associations with max phase numbers. By extending on this idea, this could be a good opportunity to introduce some ML to predict whether these zero max phase compounds would enter the approved max phase.\n\nFirstly, I had a look at the overall distribution of the max phase compounds in this dataframe df_dn.\n\n::: {.cell execution_count=13}\n``` {.python .cell-code}\n# Interested in what types of \"Max Phase\" were recorded \n# for the curated small molecules in ChEMBL database\ndf_dn.groupby(\"Max Phase\", maintain_order = True).agg(pl.count())\n```\n\n::: {.cell-output .cell-output-display execution_count=59}\n```{=html}\n<div><style>\n.dataframe > thead > tr > th,\n.dataframe > tbody > tr > td {\n  text-align: right;\n}\n</style>\n<small>shape: (5, 2)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>Max Phase</th><th>count</th></tr><tr><td>i64</td><td>u32</td></tr></thead><tbody><tr><td>0</td><td>734633</td></tr><tr><td>3</td><td>303</td></tr><tr><td>4</td><td>954</td></tr><tr><td>2</td><td>441</td></tr><tr><td>1</td><td>239</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\nA quick groupby function showed that there were only 954 small molecules approved. Phase 3 recorded a total of 303 small molecules. For phase 2, there were 441 small molecules, followed by 239 compounds in phase 1. There were, however, a total amount of 734,633 small molecules that had zero as phase number (as per ChEMBL_31 schema documentation). Note: these figures were only for ChEMBL compounds with full documentations in the dataset (excluding entries or compounds with N/A or \"\" (empty) string cells).\n\nOne of the other parameters I was interested in was \"QED Weighted\". So I went further into understanding what it meant, as the original reference was conveniently provided in the ChEMBL_31 schema documentation. The reference paper was by [Bickerton, G., Paolini, G., Besnard, J. et al. Quantifying the chemical beauty of drugs. Nature Chem 4, 90--98 (2012)](https://doi.org/10.1038/nchem.1243) (note: author's manuscript was available to view via PubMed link, the Nature Chemistry link only provided abstract with access to article via other means as stated).\n\nIn short, it was a measure of druglikeness for small molecules based on the concept of desirability, which was based on a total of 8 different molecular properties. These molecular properties included molecular weight, ALogP, polar surface area, number of hydrogen bond acceptors, number of hydrogen bond donors, number of rotatable bonds, number of aromatic rings and structural alerts. Without going into too much details for this QED Weighted parameter, it was normally recorded as a number that ranged from 0 to 1, with 0 being the least druglike and 1 being the most druglike.\n\n<br>\n\n##### **Prepare dataframe prior to running machine learning model**\n\nBefore I got too carried away with further EDA, I wanted to get started on preparing a dataframe for the ML model. A rough plan at this stage was to filter out Max Phase 4 and 0 compounds. Max phase 0 compounds were the ones that were not assigned with any max phase numbers yet, so they would be ideal for use as the testing set. Another main idea was to use \"Max Phase\" parameter as the target y variable for a LR model, because ultimately stakeholders would be more interested in knowing which candidate compounds had the most likely chance to reach the final approved phase during a drug discovery and development project or otherwise. This would also provide a chance to potentially reduce the amount of resources and time required in such a complex and sophisticated matter.\n\nThe goal of this ML model was to answer this question: which physicochemical parameters would be the most suitable ones to predict whether a compound would enter max phase 4 (approved) or not? (implicitly, this might also help to predict which max phase 0 compounds would likely enter max phase 4 in the end)\n\nI've then narrowed down the df_dn dataset to fulfill the following criteria:\n\n-   Only small molecules present\n-   Max phase of 0 and 4 only\n\nAnother reason behind choosing only small molecules that had max phase of 0 and 4 was that a confusion matrix could be built in the end to see if the parameters selected would give us a reasonably good model for predicting the outcomes of these small molecules.\n\nFor now, I've chosen the following columns (or physicochemical parameters) to appear in the interim df_0 and df_4 datasets.\n\n::: {.cell execution_count=14}\n``` {.python .cell-code}\n# Selecting Max phase 0 small molecules with desired parameters\ndf_0 = df_dn.filter(\n    (pl.col(\"Type\") == \"Small molecule\") &\n    (pl.col(\"Max Phase\") == 0)\n).select([\"ChEMBL ID\", \n          \"Type\", \n          \"Max Phase\",\n          \"#RO5 Violations\", \n          \"QED Weighted\", \n          \"CX LogP\", \n          \"CX LogD\", \n          \"Heavy Atoms\"]\n        )\ndf_0\n```\n\n::: {.cell-output .cell-output-display execution_count=60}\n```{=html}\n<div><style>\n.dataframe > thead > tr > th,\n.dataframe > tbody > tr > td {\n  text-align: right;\n}\n</style>\n<small>shape: (612_795, 8)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>ChEMBL ID</th><th>Type</th><th>Max Phase</th><th>#RO5 Violations</th><th>QED Weighted</th><th>CX LogP</th><th>CX LogD</th><th>Heavy Atoms</th></tr><tr><td>str</td><td>str</td><td>i64</td><td>i64</td><td>f64</td><td>f64</td><td>f64</td><td>i64</td></tr></thead><tbody><tr><td>&quot;CHEMBL539070&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.63</td><td>2.57</td><td>2.57</td><td>17</td></tr><tr><td>&quot;CHEMBL3827271&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>2</td><td>0.07</td><td>-6.88</td><td>-8.95</td><td>50</td></tr><tr><td>&quot;CHEMBL3824158&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>1</td><td>0.31</td><td>2.49</td><td>2.42</td><td>31</td></tr><tr><td>&quot;CHEMBL1991010&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>1</td><td>0.6</td><td>6.34</td><td>5.22</td><td>31</td></tr><tr><td>&quot;CHEMBL195644&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.73</td><td>3.92</td><td>3.91</td><td>28</td></tr><tr><td>&quot;CHEMBL255263&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.72</td><td>1.74</td><td>1.74</td><td>27</td></tr><tr><td>&quot;CHEMBL504846&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>3</td><td>0.23</td><td>3.4</td><td>2.87</td><td>58</td></tr><tr><td>&quot;CHEMBL85010&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>1</td><td>0.22</td><td>3.27</td><td>2.75</td><td>35</td></tr><tr><td>&quot;CHEMBL1364151&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.88</td><td>2.38</td><td>2.14</td><td>23</td></tr><tr><td>&quot;CHEMBL2047203&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>2</td><td>0.06</td><td>4.35</td><td>4.11</td><td>61</td></tr><tr><td>&quot;CHEMBL3798157&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.4</td><td>3.97</td><td>3.64</td><td>32</td></tr><tr><td>&quot;CHEMBL1337107&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.75</td><td>2.35</td><td>2.35</td><td>22</td></tr><tr><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td></tr><tr><td>&quot;CHEMBL255122&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>1</td><td>0.47</td><td>1.68</td><td>1.65</td><td>36</td></tr><tr><td>&quot;CHEMBL2018776&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>2</td><td>0.26</td><td>5.66</td><td>3.88</td><td>36</td></tr><tr><td>&quot;CHEMBL97207&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.89</td><td>2.1</td><td>2.1</td><td>18</td></tr><tr><td>&quot;CHEMBL221343&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>1</td><td>0.55</td><td>5.46</td><td>5.46</td><td>24</td></tr><tr><td>&quot;CHEMBL1420018&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.52</td><td>2.38</td><td>2.38</td><td>19</td></tr><tr><td>&quot;CHEMBL2314244&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>1</td><td>0.2</td><td>-0.72</td><td>-3.93</td><td>34</td></tr><tr><td>&quot;CHEMBL1420130&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.63</td><td>2.94</td><td>2.94</td><td>15</td></tr><tr><td>&quot;CHEMBL2419480&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.59</td><td>2.14</td><td>1.2</td><td>32</td></tr><tr><td>&quot;CHEMBL540121&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>1</td><td>0.22</td><td>-0.75</td><td>-0.78</td><td>36</td></tr><tr><td>&quot;CHEMBL374041&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>1</td><td>0.28</td><td>2.17</td><td>1.33</td><td>37</td></tr><tr><td>&quot;CHEMBL2017916&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.8</td><td>2.17</td><td>2.1</td><td>22</td></tr><tr><td>&quot;CHEMBL1416264&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.54</td><td>2.47</td><td>2.47</td><td>27</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n::: {.cell execution_count=15}\n``` {.python .cell-code}\n# Selecting Max phase 4 small molecules with desired parameters\ndf_4 = df_dn.filter(\n    (pl.col(\"Type\") == \"Small molecule\") &\n    (pl.col(\"Max Phase\") == 4)\n).select([\"ChEMBL ID\", \n          \"Type\", \n          \"Max Phase\",\n          \"#RO5 Violations\", \n          \"QED Weighted\", \n          \"CX LogP\", \n          \"CX LogD\", \n          \"Heavy Atoms\"]\n        )\ndf_4\n```\n\n::: {.cell-output .cell-output-display execution_count=61}\n```{=html}\n<div><style>\n.dataframe > thead > tr > th,\n.dataframe > tbody > tr > td {\n  text-align: right;\n}\n</style>\n<small>shape: (944, 8)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>ChEMBL ID</th><th>Type</th><th>Max Phase</th><th>#RO5 Violations</th><th>QED Weighted</th><th>CX LogP</th><th>CX LogD</th><th>Heavy Atoms</th></tr><tr><td>str</td><td>str</td><td>i64</td><td>i64</td><td>f64</td><td>f64</td><td>f64</td><td>i64</td></tr></thead><tbody><tr><td>&quot;CHEMBL1096882&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.31</td><td>-1.97</td><td>-5.12</td><td>24</td></tr><tr><td>&quot;CHEMBL2023898&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>2</td><td>0.14</td><td>4.18</td><td>4.16</td><td>54</td></tr><tr><td>&quot;CHEMBL1029&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.46</td><td>-1.18</td><td>-2.3</td><td>15</td></tr><tr><td>&quot;CHEMBL1616&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.72</td><td>2.88</td><td>2.58</td><td>20</td></tr><tr><td>&quot;CHEMBL2146123&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>1</td><td>0.33</td><td>-3.51</td><td>-3.81</td><td>32</td></tr><tr><td>&quot;CHEMBL1200773&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.75</td><td>1.88</td><td>1.0</td><td>14</td></tr><tr><td>&quot;CHEMBL1201002&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.77</td><td>1.42</td><td>-0.89</td><td>21</td></tr><tr><td>&quot;CHEMBL1086440&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>1</td><td>0.58</td><td>5.88</td><td>5.88</td><td>21</td></tr><tr><td>&quot;CHEMBL2359966&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.88</td><td>2.51</td><td>0.86</td><td>24</td></tr><tr><td>&quot;CHEMBL302795&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.87</td><td>-0.12</td><td>-1.91</td><td>22</td></tr><tr><td>&quot;CHEMBL1214185&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>2</td><td>0.08</td><td>3.0</td><td>1.32</td><td>58</td></tr><tr><td>&quot;CHEMBL487253&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.7</td><td>1.8</td><td>0.81</td><td>23</td></tr><tr><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td></tr><tr><td>&quot;CHEMBL2103743&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.93</td><td>1.24</td><td>1.19</td><td>23</td></tr><tr><td>&quot;CHEMBL3989931&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.46</td><td>4.59</td><td>4.59</td><td>33</td></tr><tr><td>&quot;CHEMBL1201033&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>1</td><td>0.32</td><td>3.4</td><td>1.0</td><td>19</td></tr><tr><td>&quot;CHEMBL1201731&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.69</td><td>3.21</td><td>1.71</td><td>29</td></tr><tr><td>&quot;CHEMBL2105743&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.58</td><td>1.19</td><td>-0.18</td><td>28</td></tr><tr><td>&quot;CHEMBL4297513&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>2</td><td>0.26</td><td>4.9</td><td>4.9</td><td>53</td></tr><tr><td>&quot;CHEMBL1201321&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>1</td><td>0.58</td><td>2.65</td><td>2.65</td><td>32</td></tr><tr><td>&quot;CHEMBL3545062&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>2</td><td>0.1</td><td>5.57</td><td>5.57</td><td>65</td></tr><tr><td>&quot;CHEMBL3039520&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.83</td><td>3.3</td><td>2.61</td><td>27</td></tr><tr><td>&quot;CHEMBL1198857&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.26</td><td>3.6</td><td>1.93</td><td>32</td></tr><tr><td>&quot;CHEMBL2146133&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.77</td><td>2.43</td><td>2.43</td><td>24</td></tr><tr><td>&quot;CHEMBL1619785&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.49</td><td>2.09</td><td>1.86</td><td>34</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n<br>\n\n###### **Re-sampling via under-sampling**\n\nBecause of the large number of Max Phase 0 compounds present in the original dataset, I've randomly sampled about 950 small molecules from this group, so that there were similar amount of data in each group to avoid having an imbalanced dataset.\n\n::: {.cell execution_count=16}\n``` {.python .cell-code}\ndf_s_0 = df_0.sample(n = 950, shuffle = True, seed = 0)\ndf_s_0\n```\n\n::: {.cell-output .cell-output-display execution_count=62}\n```{=html}\n<div><style>\n.dataframe > thead > tr > th,\n.dataframe > tbody > tr > td {\n  text-align: right;\n}\n</style>\n<small>shape: (950, 8)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>ChEMBL ID</th><th>Type</th><th>Max Phase</th><th>#RO5 Violations</th><th>QED Weighted</th><th>CX LogP</th><th>CX LogD</th><th>Heavy Atoms</th></tr><tr><td>str</td><td>str</td><td>i64</td><td>i64</td><td>f64</td><td>f64</td><td>f64</td><td>i64</td></tr></thead><tbody><tr><td>&quot;CHEMBL3448290&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.91</td><td>2.05</td><td>0.62</td><td>21</td></tr><tr><td>&quot;CHEMBL3966308&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>2</td><td>0.16</td><td>1.51</td><td>-0.41</td><td>48</td></tr><tr><td>&quot;CHEMBL3963545&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>2</td><td>0.2</td><td>5.05</td><td>3.27</td><td>46</td></tr><tr><td>&quot;CHEMBL1649629&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.53</td><td>3.21</td><td>3.21</td><td>24</td></tr><tr><td>&quot;CHEMBL3813954&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>1</td><td>0.14</td><td>2.8</td><td>2.8</td><td>37</td></tr><tr><td>&quot;CHEMBL1164717&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.42</td><td>1.6</td><td>1.55</td><td>35</td></tr><tr><td>&quot;CHEMBL1824896&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.58</td><td>4.69</td><td>4.13</td><td>34</td></tr><tr><td>&quot;CHEMBL2323807&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.88</td><td>3.09</td><td>2.22</td><td>20</td></tr><tr><td>&quot;CHEMBL3919258&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.5</td><td>1.36</td><td>1.36</td><td>32</td></tr><tr><td>&quot;CHEMBL1973768&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.61</td><td>-1.09</td><td>-1.09</td><td>15</td></tr><tr><td>&quot;CHEMBL3193130&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.32</td><td>2.88</td><td>2.88</td><td>30</td></tr><tr><td>&quot;CHEMBL157009&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.4</td><td>-1.57</td><td>-1.6</td><td>20</td></tr><tr><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td></tr><tr><td>&quot;CHEMBL1586774&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.79</td><td>4.03</td><td>4.02</td><td>25</td></tr><tr><td>&quot;CHEMBL3735848&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.62</td><td>2.49</td><td>2.48</td><td>31</td></tr><tr><td>&quot;CHEMBL2238035&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.63</td><td>-0.89</td><td>-0.9</td><td>18</td></tr><tr><td>&quot;CHEMBL2409594&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.42</td><td>2.9</td><td>2.9</td><td>32</td></tr><tr><td>&quot;CHEMBL1823603&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.51</td><td>4.06</td><td>4.06</td><td>32</td></tr><tr><td>&quot;CHEMBL1373723&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>2</td><td>0.25</td><td>4.85</td><td>4.84</td><td>47</td></tr><tr><td>&quot;CHEMBL1092638&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>1</td><td>0.45</td><td>5.0</td><td>4.78</td><td>34</td></tr><tr><td>&quot;CHEMBL3884327&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.23</td><td>2.0</td><td>1.31</td><td>33</td></tr><tr><td>&quot;CHEMBL3952298&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>2</td><td>0.27</td><td>4.75</td><td>4.75</td><td>37</td></tr><tr><td>&quot;CHEMBL3958658&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>1</td><td>0.37</td><td>4.32</td><td>4.32</td><td>36</td></tr><tr><td>&quot;CHEMBL2181572&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.32</td><td>3.3</td><td>3.3</td><td>23</td></tr><tr><td>&quot;CHEMBL603992&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.27</td><td>3.51</td><td>3.51</td><td>35</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\nSince the plan was to use LR method for ML model, the y variable I was interested in was going to be a binary categorical variable - meaning it needed to be 0 (not approved) or 1 (approved). To do this, I've added a new column with a new name of \"Max_Phase\" and replace \"4\" as \"1\" by dividing the whole column by 4 to reach this new label.\n\n::: {.cell execution_count=17}\n``` {.python .cell-code}\ndf_4_f = df_4.with_columns((pl.col(\"Max Phase\") / 4).alias(\"Max_Phase\"))\ndf_4_f\n```\n\n::: {.cell-output .cell-output-display execution_count=63}\n```{=html}\n<div><style>\n.dataframe > thead > tr > th,\n.dataframe > tbody > tr > td {\n  text-align: right;\n}\n</style>\n<small>shape: (944, 9)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>ChEMBL ID</th><th>Type</th><th>Max Phase</th><th>#RO5 Violations</th><th>QED Weighted</th><th>CX LogP</th><th>CX LogD</th><th>Heavy Atoms</th><th>Max_Phase</th></tr><tr><td>str</td><td>str</td><td>i64</td><td>i64</td><td>f64</td><td>f64</td><td>f64</td><td>i64</td><td>f64</td></tr></thead><tbody><tr><td>&quot;CHEMBL1096882&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.31</td><td>-1.97</td><td>-5.12</td><td>24</td><td>1.0</td></tr><tr><td>&quot;CHEMBL2023898&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>2</td><td>0.14</td><td>4.18</td><td>4.16</td><td>54</td><td>1.0</td></tr><tr><td>&quot;CHEMBL1029&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.46</td><td>-1.18</td><td>-2.3</td><td>15</td><td>1.0</td></tr><tr><td>&quot;CHEMBL1616&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.72</td><td>2.88</td><td>2.58</td><td>20</td><td>1.0</td></tr><tr><td>&quot;CHEMBL2146123&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>1</td><td>0.33</td><td>-3.51</td><td>-3.81</td><td>32</td><td>1.0</td></tr><tr><td>&quot;CHEMBL1200773&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.75</td><td>1.88</td><td>1.0</td><td>14</td><td>1.0</td></tr><tr><td>&quot;CHEMBL1201002&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.77</td><td>1.42</td><td>-0.89</td><td>21</td><td>1.0</td></tr><tr><td>&quot;CHEMBL1086440&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>1</td><td>0.58</td><td>5.88</td><td>5.88</td><td>21</td><td>1.0</td></tr><tr><td>&quot;CHEMBL2359966&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.88</td><td>2.51</td><td>0.86</td><td>24</td><td>1.0</td></tr><tr><td>&quot;CHEMBL302795&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.87</td><td>-0.12</td><td>-1.91</td><td>22</td><td>1.0</td></tr><tr><td>&quot;CHEMBL1214185&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>2</td><td>0.08</td><td>3.0</td><td>1.32</td><td>58</td><td>1.0</td></tr><tr><td>&quot;CHEMBL487253&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.7</td><td>1.8</td><td>0.81</td><td>23</td><td>1.0</td></tr><tr><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td></tr><tr><td>&quot;CHEMBL2103743&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.93</td><td>1.24</td><td>1.19</td><td>23</td><td>1.0</td></tr><tr><td>&quot;CHEMBL3989931&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.46</td><td>4.59</td><td>4.59</td><td>33</td><td>1.0</td></tr><tr><td>&quot;CHEMBL1201033&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>1</td><td>0.32</td><td>3.4</td><td>1.0</td><td>19</td><td>1.0</td></tr><tr><td>&quot;CHEMBL1201731&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.69</td><td>3.21</td><td>1.71</td><td>29</td><td>1.0</td></tr><tr><td>&quot;CHEMBL2105743&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.58</td><td>1.19</td><td>-0.18</td><td>28</td><td>1.0</td></tr><tr><td>&quot;CHEMBL4297513&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>2</td><td>0.26</td><td>4.9</td><td>4.9</td><td>53</td><td>1.0</td></tr><tr><td>&quot;CHEMBL1201321&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>1</td><td>0.58</td><td>2.65</td><td>2.65</td><td>32</td><td>1.0</td></tr><tr><td>&quot;CHEMBL3545062&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>2</td><td>0.1</td><td>5.57</td><td>5.57</td><td>65</td><td>1.0</td></tr><tr><td>&quot;CHEMBL3039520&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.83</td><td>3.3</td><td>2.61</td><td>27</td><td>1.0</td></tr><tr><td>&quot;CHEMBL1198857&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.26</td><td>3.6</td><td>1.93</td><td>32</td><td>1.0</td></tr><tr><td>&quot;CHEMBL2146133&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.77</td><td>2.43</td><td>2.43</td><td>24</td><td>1.0</td></tr><tr><td>&quot;CHEMBL1619785&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.49</td><td>2.09</td><td>1.86</td><td>34</td><td>1.0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\nThen I changed the data type of \"Max_Phase\" from float to integer, so that the two different dataframes could be concatenated (which would only work if both were of same data types).\n\n::: {.cell execution_count=18}\n``` {.python .cell-code}\ndf_4_f = df_4_f.with_columns((pl.col(\"Max_Phase\")).cast(pl.Int64, strict = False))\ndf_4_f\n```\n\n::: {.cell-output .cell-output-display execution_count=64}\n```{=html}\n<div><style>\n.dataframe > thead > tr > th,\n.dataframe > tbody > tr > td {\n  text-align: right;\n}\n</style>\n<small>shape: (944, 9)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>ChEMBL ID</th><th>Type</th><th>Max Phase</th><th>#RO5 Violations</th><th>QED Weighted</th><th>CX LogP</th><th>CX LogD</th><th>Heavy Atoms</th><th>Max_Phase</th></tr><tr><td>str</td><td>str</td><td>i64</td><td>i64</td><td>f64</td><td>f64</td><td>f64</td><td>i64</td><td>i64</td></tr></thead><tbody><tr><td>&quot;CHEMBL1096882&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.31</td><td>-1.97</td><td>-5.12</td><td>24</td><td>1</td></tr><tr><td>&quot;CHEMBL2023898&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>2</td><td>0.14</td><td>4.18</td><td>4.16</td><td>54</td><td>1</td></tr><tr><td>&quot;CHEMBL1029&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.46</td><td>-1.18</td><td>-2.3</td><td>15</td><td>1</td></tr><tr><td>&quot;CHEMBL1616&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.72</td><td>2.88</td><td>2.58</td><td>20</td><td>1</td></tr><tr><td>&quot;CHEMBL2146123&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>1</td><td>0.33</td><td>-3.51</td><td>-3.81</td><td>32</td><td>1</td></tr><tr><td>&quot;CHEMBL1200773&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.75</td><td>1.88</td><td>1.0</td><td>14</td><td>1</td></tr><tr><td>&quot;CHEMBL1201002&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.77</td><td>1.42</td><td>-0.89</td><td>21</td><td>1</td></tr><tr><td>&quot;CHEMBL1086440&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>1</td><td>0.58</td><td>5.88</td><td>5.88</td><td>21</td><td>1</td></tr><tr><td>&quot;CHEMBL2359966&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.88</td><td>2.51</td><td>0.86</td><td>24</td><td>1</td></tr><tr><td>&quot;CHEMBL302795&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.87</td><td>-0.12</td><td>-1.91</td><td>22</td><td>1</td></tr><tr><td>&quot;CHEMBL1214185&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>2</td><td>0.08</td><td>3.0</td><td>1.32</td><td>58</td><td>1</td></tr><tr><td>&quot;CHEMBL487253&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.7</td><td>1.8</td><td>0.81</td><td>23</td><td>1</td></tr><tr><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td></tr><tr><td>&quot;CHEMBL2103743&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.93</td><td>1.24</td><td>1.19</td><td>23</td><td>1</td></tr><tr><td>&quot;CHEMBL3989931&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.46</td><td>4.59</td><td>4.59</td><td>33</td><td>1</td></tr><tr><td>&quot;CHEMBL1201033&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>1</td><td>0.32</td><td>3.4</td><td>1.0</td><td>19</td><td>1</td></tr><tr><td>&quot;CHEMBL1201731&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.69</td><td>3.21</td><td>1.71</td><td>29</td><td>1</td></tr><tr><td>&quot;CHEMBL2105743&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.58</td><td>1.19</td><td>-0.18</td><td>28</td><td>1</td></tr><tr><td>&quot;CHEMBL4297513&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>2</td><td>0.26</td><td>4.9</td><td>4.9</td><td>53</td><td>1</td></tr><tr><td>&quot;CHEMBL1201321&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>1</td><td>0.58</td><td>2.65</td><td>2.65</td><td>32</td><td>1</td></tr><tr><td>&quot;CHEMBL3545062&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>2</td><td>0.1</td><td>5.57</td><td>5.57</td><td>65</td><td>1</td></tr><tr><td>&quot;CHEMBL3039520&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.83</td><td>3.3</td><td>2.61</td><td>27</td><td>1</td></tr><tr><td>&quot;CHEMBL1198857&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.26</td><td>3.6</td><td>1.93</td><td>32</td><td>1</td></tr><tr><td>&quot;CHEMBL2146133&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.77</td><td>2.43</td><td>2.43</td><td>24</td><td>1</td></tr><tr><td>&quot;CHEMBL1619785&quot;</td><td>&quot;Small molecule…</td><td>4</td><td>0</td><td>0.49</td><td>2.09</td><td>1.86</td><td>34</td><td>1</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\nAlso I've created a new column with the same name of \"Max_Phase\" for Max phase 0 small molecules, so that the two dataframes could be combined (also needed to have exactly the same column names for it to work).\n\n::: {.cell execution_count=19}\n``` {.python .cell-code}\ndf_s_0_f = df_s_0.with_columns((pl.col(\"Max Phase\")).alias(\"Max_Phase\"))\ndf_s_0_f\n```\n\n::: {.cell-output .cell-output-display execution_count=65}\n```{=html}\n<div><style>\n.dataframe > thead > tr > th,\n.dataframe > tbody > tr > td {\n  text-align: right;\n}\n</style>\n<small>shape: (950, 9)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>ChEMBL ID</th><th>Type</th><th>Max Phase</th><th>#RO5 Violations</th><th>QED Weighted</th><th>CX LogP</th><th>CX LogD</th><th>Heavy Atoms</th><th>Max_Phase</th></tr><tr><td>str</td><td>str</td><td>i64</td><td>i64</td><td>f64</td><td>f64</td><td>f64</td><td>i64</td><td>i64</td></tr></thead><tbody><tr><td>&quot;CHEMBL3448290&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.91</td><td>2.05</td><td>0.62</td><td>21</td><td>0</td></tr><tr><td>&quot;CHEMBL3966308&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>2</td><td>0.16</td><td>1.51</td><td>-0.41</td><td>48</td><td>0</td></tr><tr><td>&quot;CHEMBL3963545&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>2</td><td>0.2</td><td>5.05</td><td>3.27</td><td>46</td><td>0</td></tr><tr><td>&quot;CHEMBL1649629&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.53</td><td>3.21</td><td>3.21</td><td>24</td><td>0</td></tr><tr><td>&quot;CHEMBL3813954&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>1</td><td>0.14</td><td>2.8</td><td>2.8</td><td>37</td><td>0</td></tr><tr><td>&quot;CHEMBL1164717&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.42</td><td>1.6</td><td>1.55</td><td>35</td><td>0</td></tr><tr><td>&quot;CHEMBL1824896&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.58</td><td>4.69</td><td>4.13</td><td>34</td><td>0</td></tr><tr><td>&quot;CHEMBL2323807&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.88</td><td>3.09</td><td>2.22</td><td>20</td><td>0</td></tr><tr><td>&quot;CHEMBL3919258&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.5</td><td>1.36</td><td>1.36</td><td>32</td><td>0</td></tr><tr><td>&quot;CHEMBL1973768&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.61</td><td>-1.09</td><td>-1.09</td><td>15</td><td>0</td></tr><tr><td>&quot;CHEMBL3193130&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.32</td><td>2.88</td><td>2.88</td><td>30</td><td>0</td></tr><tr><td>&quot;CHEMBL157009&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.4</td><td>-1.57</td><td>-1.6</td><td>20</td><td>0</td></tr><tr><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td></tr><tr><td>&quot;CHEMBL1586774&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.79</td><td>4.03</td><td>4.02</td><td>25</td><td>0</td></tr><tr><td>&quot;CHEMBL3735848&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.62</td><td>2.49</td><td>2.48</td><td>31</td><td>0</td></tr><tr><td>&quot;CHEMBL2238035&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.63</td><td>-0.89</td><td>-0.9</td><td>18</td><td>0</td></tr><tr><td>&quot;CHEMBL2409594&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.42</td><td>2.9</td><td>2.9</td><td>32</td><td>0</td></tr><tr><td>&quot;CHEMBL1823603&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.51</td><td>4.06</td><td>4.06</td><td>32</td><td>0</td></tr><tr><td>&quot;CHEMBL1373723&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>2</td><td>0.25</td><td>4.85</td><td>4.84</td><td>47</td><td>0</td></tr><tr><td>&quot;CHEMBL1092638&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>1</td><td>0.45</td><td>5.0</td><td>4.78</td><td>34</td><td>0</td></tr><tr><td>&quot;CHEMBL3884327&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.23</td><td>2.0</td><td>1.31</td><td>33</td><td>0</td></tr><tr><td>&quot;CHEMBL3952298&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>2</td><td>0.27</td><td>4.75</td><td>4.75</td><td>37</td><td>0</td></tr><tr><td>&quot;CHEMBL3958658&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>1</td><td>0.37</td><td>4.32</td><td>4.32</td><td>36</td><td>0</td></tr><tr><td>&quot;CHEMBL2181572&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.32</td><td>3.3</td><td>3.3</td><td>23</td><td>0</td></tr><tr><td>&quot;CHEMBL603992&quot;</td><td>&quot;Small molecule…</td><td>0</td><td>0</td><td>0.27</td><td>3.51</td><td>3.51</td><td>35</td><td>0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\nThen I combined df_s\\_0_f (dataframe with max phase 0 compounds) and df_4\\_f (dataframe with max phase 4 compounds).\n\n::: {.cell execution_count=20}\n``` {.python .cell-code}\ndf_concat = pl.concat([df_s_0_f, df_4_f], how = \"vertical\",)\nprint(df_concat)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nshape: (1_894, 9)\n┌───────────────┬──────────┬───────────┬────────────┬───┬─────────┬─────────┬───────┬───────────┐\n│ ChEMBL ID     ┆ Type     ┆ Max Phase ┆ #RO5       ┆ … ┆ CX LogP ┆ CX LogD ┆ Heavy ┆ Max_Phase │\n│ ---           ┆ ---      ┆ ---       ┆ Violations ┆   ┆ ---     ┆ ---     ┆ Atoms ┆ ---       │\n│ str           ┆ str      ┆ i64       ┆ ---        ┆   ┆ f64     ┆ f64     ┆ ---   ┆ i64       │\n│               ┆          ┆           ┆ i64        ┆   ┆         ┆         ┆ i64   ┆           │\n╞═══════════════╪══════════╪═══════════╪════════════╪═══╪═════════╪═════════╪═══════╪═══════════╡\n│ CHEMBL3448290 ┆ Small    ┆ 0         ┆ 0          ┆ … ┆ 2.05    ┆ 0.62    ┆ 21    ┆ 0         │\n│               ┆ molecule ┆           ┆            ┆   ┆         ┆         ┆       ┆           │\n│ CHEMBL3966308 ┆ Small    ┆ 0         ┆ 2          ┆ … ┆ 1.51    ┆ -0.41   ┆ 48    ┆ 0         │\n│               ┆ molecule ┆           ┆            ┆   ┆         ┆         ┆       ┆           │\n│ CHEMBL3963545 ┆ Small    ┆ 0         ┆ 2          ┆ … ┆ 5.05    ┆ 3.27    ┆ 46    ┆ 0         │\n│               ┆ molecule ┆           ┆            ┆   ┆         ┆         ┆       ┆           │\n│ CHEMBL1649629 ┆ Small    ┆ 0         ┆ 0          ┆ … ┆ 3.21    ┆ 3.21    ┆ 24    ┆ 0         │\n│               ┆ molecule ┆           ┆            ┆   ┆         ┆         ┆       ┆           │\n│ …             ┆ …        ┆ …         ┆ …          ┆ … ┆ …       ┆ …       ┆ …     ┆ …         │\n│ CHEMBL3039520 ┆ Small    ┆ 4         ┆ 0          ┆ … ┆ 3.3     ┆ 2.61    ┆ 27    ┆ 1         │\n│               ┆ molecule ┆           ┆            ┆   ┆         ┆         ┆       ┆           │\n│ CHEMBL1198857 ┆ Small    ┆ 4         ┆ 0          ┆ … ┆ 3.6     ┆ 1.93    ┆ 32    ┆ 1         │\n│               ┆ molecule ┆           ┆            ┆   ┆         ┆         ┆       ┆           │\n│ CHEMBL2146133 ┆ Small    ┆ 4         ┆ 0          ┆ … ┆ 2.43    ┆ 2.43    ┆ 24    ┆ 1         │\n│               ┆ molecule ┆           ┆            ┆   ┆         ┆         ┆       ┆           │\n│ CHEMBL1619785 ┆ Small    ┆ 4         ┆ 0          ┆ … ┆ 2.09    ┆ 1.86    ┆ 34    ┆ 1         │\n│               ┆ molecule ┆           ┆            ┆   ┆         ┆         ┆       ┆           │\n└───────────────┴──────────┴───────────┴────────────┴───┴─────────┴─────────┴───────┴───────────┘\n```\n:::\n:::\n\n\nThis df_concat dataset was checked to see it had all compounds in Max Phase 0 and 4 only. Note: Max Phase 4 (approved) compounds were re-labelled as Max_Phase = 1.\n\n::: {.cell execution_count=21}\n``` {.python .cell-code}\ndf_concat.groupby(\"Max_Phase\").count()\n```\n\n::: {.cell-output .cell-output-display execution_count=67}\n```{=html}\n<div><style>\n.dataframe > thead > tr > th,\n.dataframe > tbody > tr > td {\n  text-align: right;\n}\n</style>\n<small>shape: (2, 2)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>Max_Phase</th><th>count</th></tr><tr><td>i64</td><td>u32</td></tr></thead><tbody><tr><td>0</td><td>950</td></tr><tr><td>1</td><td>944</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\nI then checked df_concat dataset only had small molecules to confirm what I've tried to achieve.\n\n::: {.cell execution_count=22}\n``` {.python .cell-code}\ndf_concat.groupby(\"Type\").count()\n```\n\n::: {.cell-output .cell-output-display execution_count=68}\n```{=html}\n<div><style>\n.dataframe > thead > tr > th,\n.dataframe > tbody > tr > td {\n  text-align: right;\n}\n</style>\n<small>shape: (1, 2)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>Type</th><th>count</th></tr><tr><td>str</td><td>u32</td></tr></thead><tbody><tr><td>&quot;Small molecule…</td><td>1894</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\nSo here we had the final version of the dataset, which I've renamed to df_ml to avoid confusion from the previous dataframes, before entering the ML phase.\n\n::: {.cell execution_count=23}\n``` {.python .cell-code}\n# Leave out ChEMBL ID and Type\ndf_ml = df_concat.select([\"Max_Phase\", \n                          \"#RO5 Violations\", \n                          \"QED Weighted\", \n                          \"CX LogP\", \n                          \"CX LogD\", \n                          \"Heavy Atoms\"]\n                        )\ndf_ml\n```\n\n::: {.cell-output .cell-output-display execution_count=69}\n```{=html}\n<div><style>\n.dataframe > thead > tr > th,\n.dataframe > tbody > tr > td {\n  text-align: right;\n}\n</style>\n<small>shape: (1_894, 6)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>Max_Phase</th><th>#RO5 Violations</th><th>QED Weighted</th><th>CX LogP</th><th>CX LogD</th><th>Heavy Atoms</th></tr><tr><td>i64</td><td>i64</td><td>f64</td><td>f64</td><td>f64</td><td>i64</td></tr></thead><tbody><tr><td>0</td><td>0</td><td>0.91</td><td>2.05</td><td>0.62</td><td>21</td></tr><tr><td>0</td><td>2</td><td>0.16</td><td>1.51</td><td>-0.41</td><td>48</td></tr><tr><td>0</td><td>2</td><td>0.2</td><td>5.05</td><td>3.27</td><td>46</td></tr><tr><td>0</td><td>0</td><td>0.53</td><td>3.21</td><td>3.21</td><td>24</td></tr><tr><td>0</td><td>1</td><td>0.14</td><td>2.8</td><td>2.8</td><td>37</td></tr><tr><td>0</td><td>0</td><td>0.42</td><td>1.6</td><td>1.55</td><td>35</td></tr><tr><td>0</td><td>0</td><td>0.58</td><td>4.69</td><td>4.13</td><td>34</td></tr><tr><td>0</td><td>0</td><td>0.88</td><td>3.09</td><td>2.22</td><td>20</td></tr><tr><td>0</td><td>0</td><td>0.5</td><td>1.36</td><td>1.36</td><td>32</td></tr><tr><td>0</td><td>0</td><td>0.61</td><td>-1.09</td><td>-1.09</td><td>15</td></tr><tr><td>0</td><td>0</td><td>0.32</td><td>2.88</td><td>2.88</td><td>30</td></tr><tr><td>0</td><td>0</td><td>0.4</td><td>-1.57</td><td>-1.6</td><td>20</td></tr><tr><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td><td>&hellip;</td></tr><tr><td>1</td><td>0</td><td>0.93</td><td>1.24</td><td>1.19</td><td>23</td></tr><tr><td>1</td><td>0</td><td>0.46</td><td>4.59</td><td>4.59</td><td>33</td></tr><tr><td>1</td><td>1</td><td>0.32</td><td>3.4</td><td>1.0</td><td>19</td></tr><tr><td>1</td><td>0</td><td>0.69</td><td>3.21</td><td>1.71</td><td>29</td></tr><tr><td>1</td><td>0</td><td>0.58</td><td>1.19</td><td>-0.18</td><td>28</td></tr><tr><td>1</td><td>2</td><td>0.26</td><td>4.9</td><td>4.9</td><td>53</td></tr><tr><td>1</td><td>1</td><td>0.58</td><td>2.65</td><td>2.65</td><td>32</td></tr><tr><td>1</td><td>2</td><td>0.1</td><td>5.57</td><td>5.57</td><td>65</td></tr><tr><td>1</td><td>0</td><td>0.83</td><td>3.3</td><td>2.61</td><td>27</td></tr><tr><td>1</td><td>0</td><td>0.26</td><td>3.6</td><td>1.93</td><td>32</td></tr><tr><td>1</td><td>0</td><td>0.77</td><td>2.43</td><td>2.43</td><td>24</td></tr><tr><td>1</td><td>0</td><td>0.49</td><td>2.09</td><td>1.86</td><td>34</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n::: {.cell execution_count=24}\n``` {.python .cell-code}\n# Check for any nulls in the dataset\ndf_ml.null_count()\n```\n\n::: {.cell-output .cell-output-display execution_count=70}\n```{=html}\n<div><style>\n.dataframe > thead > tr > th,\n.dataframe > tbody > tr > td {\n  text-align: right;\n}\n</style>\n<small>shape: (1, 6)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>Max_Phase</th><th>#RO5 Violations</th><th>QED Weighted</th><th>CX LogP</th><th>CX LogD</th><th>Heavy Atoms</th></tr><tr><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td><td>u32</td></tr></thead><tbody><tr><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n::: {.cell execution_count=25}\n``` {.python .cell-code}\n# Check data types in df_ml dataset\n# Needed to be integers or floats for scikit-learn algorithms to work\ndf_ml.dtypes\n```\n\n::: {.cell-output .cell-output-display execution_count=71}\n```\n[Int64, Int64, Float64, Float64, Float64, Int64]\n```\n:::\n:::\n\n\n``` {{python}}\n# Note: exported df_ml dataframe as csv file for ML series 2.\ndf_ml.write_csv(\"df_ml.csv\", sep = \",\")\n```\n\n<br>\n\n##### **Import libraries for machine learning**\n\n::: {.cell execution_count=26}\n``` {.python .cell-code}\n# Install scikit-learn - an open-source ML library\n# Uncomment the line below if needing to install this library\n#!pip install -U scikit-learn\n```\n:::\n\n\n::: {.cell execution_count=27}\n``` {.python .cell-code}\n# Import scikit-learn\nimport sklearn\n\n# Check version of scikit-learn \nprint(sklearn.__version__)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n1.3.0\n```\n:::\n:::\n\n\nOther libraries needed to generate ML model were imported as below.\n\n::: {.cell execution_count=28}\n``` {.python .cell-code}\n# To use NumPy arrays to prepare X & y variables\nimport numpy as np\n\n# Needed for dataframe in scikit-learn ML\n# Uncomment line below if requiring to install pandas\n#!pip install pandas\nimport pandas as pd\n\n# To normalise dataset prior to running ML\nfrom sklearn import preprocessing\n# To split dataset into training & testing sets\nfrom sklearn.model_selection import train_test_split\n\n# For data visualisations\n# Uncomment line below if requiring to install matplotlib\n#!pip install matplotlib\nimport matplotlib.pyplot as plt\n```\n:::\n\n\nI've then installed pyarrow, to convert Polars dataframe into a Pandas dataframe, which was needed to run *scikit-learn*.\n\n::: {.cell execution_count=29}\n``` {.python .cell-code}\n# Uncomment line below to install pyarrow\n#!pip install pyarrow\n```\n:::\n\n\n::: {.cell execution_count=30}\n``` {.python .cell-code}\n# Convert Polars df to Pandas df \ndf_ml_pd = df_ml.to_pandas()\ntype(df_ml_pd)\n```\n\n::: {.cell-output .cell-output-display execution_count=76}\n```\npandas.core.frame.DataFrame\n```\n:::\n:::\n\n\n<br>\n\n##### **Logistic regression with *scikit-learn***\n\nLR was one of the supervised methods in statistical ML realm. As the term \"supervised\" suggested, this type of ML was purely data-driven to allow computers to learn patterns from input data with known outcomes, in order to predict new outcomes on novel data.\n\n<br>\n\n###### **Defining X and y variables**\n\n::: {.cell execution_count=31}\n``` {.python .cell-code}\n# Define X variables from df_ml_pd dataset\nX = np.asarray(df_ml_pd[[\"#RO5 Violations\", \n                         \"QED Weighted\", \n                         \"CX LogP\", \n                         \"CX LogD\", \n                         \"Heavy Atoms\"]]\n              )\nX[0:5]\n```\n\n::: {.cell-output .cell-output-display execution_count=77}\n```\narray([[ 0.  ,  0.91,  2.05,  0.62, 21.  ],\n       [ 2.  ,  0.16,  1.51, -0.41, 48.  ],\n       [ 2.  ,  0.2 ,  5.05,  3.27, 46.  ],\n       [ 0.  ,  0.53,  3.21,  3.21, 24.  ],\n       [ 1.  ,  0.14,  2.8 ,  2.8 , 37.  ]])\n```\n:::\n:::\n\n\n::: {.cell execution_count=32}\n``` {.python .cell-code}\n# Define y variable\n# Note to use \"Max_Phase\", not the original \"Max Phase\"\ny = np.asarray(df_ml_pd[\"Max_Phase\"])\ny[0:5]\n```\n\n::: {.cell-output .cell-output-display execution_count=78}\n```\narray([0, 0, 0, 0, 0])\n```\n:::\n:::\n\n\n<br>\n\n###### **Training and testing sets**\n\n::: {.cell execution_count=33}\n``` {.python .cell-code}\n# Split dataset into training & testing sets\n\n# Random number generator\n#rng = np.random.RandomState(0) - note: this may produce different result each time\n\n# Edited post to use random_state = 250 to show comparison with ML series 2\n# for reproducible result\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 250)\nprint('Training set:', X_train.shape, y_train.shape)\nprint('Testing set:', X_test.shape, y_test.shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTraining set: (1515, 5) (1515,)\nTesting set: (379, 5) (379,)\n```\n:::\n:::\n\n\n<br>\n\n###### **Preprocessing data**\n\n::: {.cell execution_count=34}\n``` {.python .cell-code}\n# Normalise & clean the dataset\n# Fit on the training set - not on testing set as this might lead to data leakage\n# Transform on the testing set\nX = preprocessing.StandardScaler().fit(X_train).transform(X_test)\nX[0:5]\n```\n\n::: {.cell-output .cell-output-display execution_count=80}\n```\narray([[-0.62, -0.8 ,  0.58,  0.76,  0.48],\n       [-0.62, -1.24,  1.27,  1.26,  0.38],\n       [-0.62,  0.49, -0.18,  0.13, -1.27],\n       [-0.62, -0.8 ,  0.03,  0.28, -0.69],\n       [-0.62, -0.48,  0.62,  0.8 , -0.2 ]])\n```\n:::\n:::\n\n\n<br>\n\n###### **Fitting LR classifier on training set**\n\n::: {.cell execution_count=35}\n``` {.python .cell-code}\n# Import logistic regression \nfrom sklearn.linear_model import LogisticRegression\n# Create an instance of logistic regression classifier and fit the data\nLogR = LogisticRegression().fit(X_train, y_train)\nLogR\n```\n\n::: {.cell-output .cell-output-display execution_count=81}\n```{=html}\n<style>#sk-container-id-3 {color: black;}#sk-container-id-3 pre{padding: 0;}#sk-container-id-3 div.sk-toggleable {background-color: white;}#sk-container-id-3 label.sk-toggleable__label {cursor: pointer;display: block;width: 100%;margin-bottom: 0;padding: 0.3em;box-sizing: border-box;text-align: center;}#sk-container-id-3 label.sk-toggleable__label-arrow:before {content: \"▸\";float: left;margin-right: 0.25em;color: #696969;}#sk-container-id-3 label.sk-toggleable__label-arrow:hover:before {color: black;}#sk-container-id-3 div.sk-estimator:hover label.sk-toggleable__label-arrow:before {color: black;}#sk-container-id-3 div.sk-toggleable__content {max-height: 0;max-width: 0;overflow: hidden;text-align: left;background-color: #f0f8ff;}#sk-container-id-3 div.sk-toggleable__content pre {margin: 0.2em;color: black;border-radius: 0.25em;background-color: #f0f8ff;}#sk-container-id-3 input.sk-toggleable__control:checked~div.sk-toggleable__content {max-height: 200px;max-width: 100%;overflow: auto;}#sk-container-id-3 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {content: \"▾\";}#sk-container-id-3 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-3 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-3 input.sk-hidden--visually {border: 0;clip: rect(1px 1px 1px 1px);clip: rect(1px, 1px, 1px, 1px);height: 1px;margin: -1px;overflow: hidden;padding: 0;position: absolute;width: 1px;}#sk-container-id-3 div.sk-estimator {font-family: monospace;background-color: #f0f8ff;border: 1px dotted black;border-radius: 0.25em;box-sizing: border-box;margin-bottom: 0.5em;}#sk-container-id-3 div.sk-estimator:hover {background-color: #d4ebff;}#sk-container-id-3 div.sk-parallel-item::after {content: \"\";width: 100%;border-bottom: 1px solid gray;flex-grow: 1;}#sk-container-id-3 div.sk-label:hover label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-3 div.sk-serial::before {content: \"\";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: 0;}#sk-container-id-3 div.sk-serial {display: flex;flex-direction: column;align-items: center;background-color: white;padding-right: 0.2em;padding-left: 0.2em;position: relative;}#sk-container-id-3 div.sk-item {position: relative;z-index: 1;}#sk-container-id-3 div.sk-parallel {display: flex;align-items: stretch;justify-content: center;background-color: white;position: relative;}#sk-container-id-3 div.sk-item::before, #sk-container-id-3 div.sk-parallel-item::before {content: \"\";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: -1;}#sk-container-id-3 div.sk-parallel-item {display: flex;flex-direction: column;z-index: 1;position: relative;background-color: white;}#sk-container-id-3 div.sk-parallel-item:first-child::after {align-self: flex-end;width: 50%;}#sk-container-id-3 div.sk-parallel-item:last-child::after {align-self: flex-start;width: 50%;}#sk-container-id-3 div.sk-parallel-item:only-child::after {width: 0;}#sk-container-id-3 div.sk-dashed-wrapped {border: 1px dashed gray;margin: 0 0.4em 0.5em 0.4em;box-sizing: border-box;padding-bottom: 0.4em;background-color: white;}#sk-container-id-3 div.sk-label label {font-family: monospace;font-weight: bold;display: inline-block;line-height: 1.2em;}#sk-container-id-3 div.sk-label-container {text-align: center;}#sk-container-id-3 div.sk-container {/* jupyter's `normalize.less` sets `[hidden] { display: none; }` but bootstrap.min.css set `[hidden] { display: none !important; }` so we also need the `!important` here to be able to override the default hidden behavior on the sphinx rendered scikit-learn.org. See: https://github.com/scikit-learn/scikit-learn/issues/21755 */display: inline-block !important;position: relative;}#sk-container-id-3 div.sk-text-repr-fallback {display: none;}</style><div id=\"sk-container-id-3\" class=\"sk-top-container\"><div class=\"sk-text-repr-fallback\"><pre>LogisticRegression()</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br />On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class=\"sk-container\" hidden><div class=\"sk-item\"><div class=\"sk-estimator sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-5\" type=\"checkbox\" checked><label for=\"sk-estimator-id-5\" class=\"sk-toggleable__label sk-toggleable__label-arrow\">LogisticRegression</label><div class=\"sk-toggleable__content\"><pre>LogisticRegression()</pre></div></div></div></div></div>\n```\n:::\n:::\n\n\n<br>\n\n###### **Applying LR classifier on testing set for prediction**\n\n::: {.cell execution_count=36}\n``` {.python .cell-code}\ny_mp = LogR.predict(X_test)\ny_mp\n```\n\n::: {.cell-output .cell-output-display execution_count=82}\n```\narray([0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,\n       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,\n       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,\n       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,\n       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,\n       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,\n       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,\n       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,\n       0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,\n       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,\n       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,\n       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,\n       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,\n       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,\n       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,\n       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,\n       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,\n       0, 0, 1, 0, 0])\n```\n:::\n:::\n\n\n<br>\n\n###### **Converting predicted values into a dataframe**\n\n::: {.cell execution_count=37}\n``` {.python .cell-code}\n# Predicted values were based on log odds\n# Use describe() method to get characteristics of the distribution\npred = pd.DataFrame(LogR.predict_log_proba(X))\npred.describe()\n```\n\n::: {.cell-output .cell-output-display execution_count=83}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>0</th>\n      <th>1</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>379.000000</td>\n      <td>379.000000</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>-0.816092</td>\n      <td>-0.719514</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>0.419447</td>\n      <td>0.386759</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>-1.845917</td>\n      <td>-1.981267</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>-1.085309</td>\n      <td>-0.966916</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>-0.732457</td>\n      <td>-0.655325</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>-0.478445</td>\n      <td>-0.412184</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>-0.148378</td>\n      <td>-0.171833</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nAlternatively, a quicker way to get predicted probabilities was via predict_proba() method in *scikit-learn*.\n\n::: {.cell execution_count=38}\n``` {.python .cell-code}\ny_mp_proba = LogR.predict_proba(X_test)\n# Uncomment below to see the predicted probabilities printed\n#print(y_mp_proba)\n```\n:::\n\n\n<br>\n\n###### **Converting predicted probabilities into a dataframe**\n\n::: {.cell execution_count=39}\n``` {.python .cell-code}\n# Use describe() to show distributions\ny_mp_prob = pd.DataFrame(y_mp_proba)\ny_mp_prob.describe()\n```\n\n::: {.cell-output .cell-output-display execution_count=85}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>0</th>\n      <th>1</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>379.000000</td>\n      <td>379.000000</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>0.483444</td>\n      <td>0.516556</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>0.178763</td>\n      <td>0.178763</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>0.006530</td>\n      <td>0.141583</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>0.354201</td>\n      <td>0.385328</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>0.502085</td>\n      <td>0.497915</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>0.614672</td>\n      <td>0.645799</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>0.858417</td>\n      <td>0.993470</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n<br>\n\n###### **Pipeline method for LR**\n\nThis was something I thought to try when I was reading through *scikit-learn* documentation. One major advantage of using pipeline was that it was designed to chain all the estimators used for ML. The benefit of this was that we only had to call fit and predict once in our data to fit the whole chain of estimators. The other useful thing was that this could avoid data leakage from our testing set into the training set by making sure the same set of samples were used to train the transformers and predictors. One other key thing it also helped was that it also avoided the possibility of missing out on the transformation step.\n\nThe example below used the function of make_pipeline, which took in a number of estimators as inputted, and then constructed a pipeline based on them.\n\n::: {.cell execution_count=40}\n``` {.python .cell-code}\n# Test pipline from scikit-Learn\nfrom sklearn.pipeline import make_pipeline\nfrom sklearn.preprocessing import StandardScaler\n\nLR = make_pipeline(StandardScaler(), LogisticRegression())\nLR.fit(X_train, y_train)\n```\n\n::: {.cell-output .cell-output-display execution_count=86}\n```{=html}\n<style>#sk-container-id-4 {color: black;}#sk-container-id-4 pre{padding: 0;}#sk-container-id-4 div.sk-toggleable {background-color: white;}#sk-container-id-4 label.sk-toggleable__label {cursor: pointer;display: block;width: 100%;margin-bottom: 0;padding: 0.3em;box-sizing: border-box;text-align: center;}#sk-container-id-4 label.sk-toggleable__label-arrow:before {content: \"▸\";float: left;margin-right: 0.25em;color: #696969;}#sk-container-id-4 label.sk-toggleable__label-arrow:hover:before {color: black;}#sk-container-id-4 div.sk-estimator:hover label.sk-toggleable__label-arrow:before {color: black;}#sk-container-id-4 div.sk-toggleable__content {max-height: 0;max-width: 0;overflow: hidden;text-align: left;background-color: #f0f8ff;}#sk-container-id-4 div.sk-toggleable__content pre {margin: 0.2em;color: black;border-radius: 0.25em;background-color: #f0f8ff;}#sk-container-id-4 input.sk-toggleable__control:checked~div.sk-toggleable__content {max-height: 200px;max-width: 100%;overflow: auto;}#sk-container-id-4 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {content: \"▾\";}#sk-container-id-4 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-4 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-4 input.sk-hidden--visually {border: 0;clip: rect(1px 1px 1px 1px);clip: rect(1px, 1px, 1px, 1px);height: 1px;margin: -1px;overflow: hidden;padding: 0;position: absolute;width: 1px;}#sk-container-id-4 div.sk-estimator {font-family: monospace;background-color: #f0f8ff;border: 1px dotted black;border-radius: 0.25em;box-sizing: border-box;margin-bottom: 0.5em;}#sk-container-id-4 div.sk-estimator:hover {background-color: #d4ebff;}#sk-container-id-4 div.sk-parallel-item::after {content: \"\";width: 100%;border-bottom: 1px solid gray;flex-grow: 1;}#sk-container-id-4 div.sk-label:hover label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-4 div.sk-serial::before {content: \"\";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: 0;}#sk-container-id-4 div.sk-serial {display: flex;flex-direction: column;align-items: center;background-color: white;padding-right: 0.2em;padding-left: 0.2em;position: relative;}#sk-container-id-4 div.sk-item {position: relative;z-index: 1;}#sk-container-id-4 div.sk-parallel {display: flex;align-items: stretch;justify-content: center;background-color: white;position: relative;}#sk-container-id-4 div.sk-item::before, #sk-container-id-4 div.sk-parallel-item::before {content: \"\";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: -1;}#sk-container-id-4 div.sk-parallel-item {display: flex;flex-direction: column;z-index: 1;position: relative;background-color: white;}#sk-container-id-4 div.sk-parallel-item:first-child::after {align-self: flex-end;width: 50%;}#sk-container-id-4 div.sk-parallel-item:last-child::after {align-self: flex-start;width: 50%;}#sk-container-id-4 div.sk-parallel-item:only-child::after {width: 0;}#sk-container-id-4 div.sk-dashed-wrapped {border: 1px dashed gray;margin: 0 0.4em 0.5em 0.4em;box-sizing: border-box;padding-bottom: 0.4em;background-color: white;}#sk-container-id-4 div.sk-label label {font-family: monospace;font-weight: bold;display: inline-block;line-height: 1.2em;}#sk-container-id-4 div.sk-label-container {text-align: center;}#sk-container-id-4 div.sk-container {/* jupyter's `normalize.less` sets `[hidden] { display: none; }` but bootstrap.min.css set `[hidden] { display: none !important; }` so we also need the `!important` here to be able to override the default hidden behavior on the sphinx rendered scikit-learn.org. See: https://github.com/scikit-learn/scikit-learn/issues/21755 */display: inline-block !important;position: relative;}#sk-container-id-4 div.sk-text-repr-fallback {display: none;}</style><div id=\"sk-container-id-4\" class=\"sk-top-container\"><div class=\"sk-text-repr-fallback\"><pre>Pipeline(steps=[(&#x27;standardscaler&#x27;, StandardScaler()),\n                (&#x27;logisticregression&#x27;, LogisticRegression())])</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br />On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class=\"sk-container\" hidden><div class=\"sk-item sk-dashed-wrapped\"><div class=\"sk-label-container\"><div class=\"sk-label sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-6\" type=\"checkbox\" ><label for=\"sk-estimator-id-6\" class=\"sk-toggleable__label sk-toggleable__label-arrow\">Pipeline</label><div class=\"sk-toggleable__content\"><pre>Pipeline(steps=[(&#x27;standardscaler&#x27;, StandardScaler()),\n                (&#x27;logisticregression&#x27;, LogisticRegression())])</pre></div></div></div><div class=\"sk-serial\"><div class=\"sk-item\"><div class=\"sk-estimator sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-7\" type=\"checkbox\" ><label for=\"sk-estimator-id-7\" class=\"sk-toggleable__label sk-toggleable__label-arrow\">StandardScaler</label><div class=\"sk-toggleable__content\"><pre>StandardScaler()</pre></div></div></div><div class=\"sk-item\"><div class=\"sk-estimator sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-8\" type=\"checkbox\" ><label for=\"sk-estimator-id-8\" class=\"sk-toggleable__label sk-toggleable__label-arrow\">LogisticRegression</label><div class=\"sk-toggleable__content\"><pre>LogisticRegression()</pre></div></div></div></div></div></div></div>\n```\n:::\n:::\n\n\n<br>\n\n#### **Evaluation of the logistic regression model**\n\n###### **Accuracy scores**\n\n::: {.cell execution_count=41}\n``` {.python .cell-code}\nfrom sklearn.metrics import accuracy_score\naccuracy_score(y_mp, y_test)\n```\n\n::: {.cell-output .cell-output-display execution_count=87}\n```\n0.6992084432717678\n```\n:::\n:::\n\n\nThe accuracy score was 0.7 (after rounding up) based on the original data preprocessing method, which meant that there were around 70% of the cases (or compounds) classified correctly by using this LR classifier. Accuracy literally provided a measure of how close the predicted samples were to the true values. One caveat to note was that for imbalanced dataset, accuracy score might not be very informative, and other evaluation metrics would need to be considered instead.\n\nThe accuracy score shown below was from the pipeline method used previously, which showed a very similar accuracy score of 0.69656992 (close to 0.7), confirming the method was in line with the original preprocessing method.\n\n::: {.cell execution_count=42}\n``` {.python .cell-code}\nLR.score(X_test, y_test)\n```\n\n::: {.cell-output .cell-output-display execution_count=88}\n```\n0.6965699208443272\n```\n:::\n:::\n\n\n<br>\n\n###### **Confusion matrix**\n\nNext, I've built a confusion matrix based on the model in order to visualise the counts of correct and incorrect predictions. The function code used below was adapted from the IBM data science course I've taken around the end of last year. I've added comments to try and explain what each section of the code meant.\n\n::: {.cell execution_count=43}\n``` {.python .cell-code}\n# Import confusion matrix from scikit-learn\nfrom sklearn.metrics import confusion_matrix\n# Import itertools - functions to create iterators for efficient looping\nimport itertools\n\n# Function to print and plot confusion matrix\ndef plot_confusion_matrix(# Sets a cm object (cm = confusion matrix)\n                          cm, \n                          # Sets classes of '1s' (Successes) & '0s' (Non-successes) for the cm\n                          classes,\n                          # If setting normalize = true, reports in ratios instead of counts\n                          normalize,\n                          title = 'Confusion matrix',\n                          # Choose colour of the cm (using colourmap recognised by matplotlib)\n                          cmap = plt.cm.Reds):\n    \n    if normalize:\n        cm = cm.astype('float') / cm.sum(axis = 1)[:, np.newaxis]\n        print(\"Normalized confusion matrix\")\n    else:\n        print('Confusion matrix, without normalization')\n\n    print(cm)\n\n    # Plot the confusion matrix \n    plt.imshow(cm, interpolation = 'nearest', cmap = cmap)\n    plt.title(title)\n    plt.colorbar()\n    tick_marks = np.arange(len(classes))\n    plt.xticks(tick_marks, classes, rotation = 45)\n    plt.yticks(tick_marks, classes)\n\n    # Floats to be round up to two decimal places if using normalize = True\n    # or else use integers\n    fmt = '.2f' if normalize else 'd'\n    # Sets threshold of 0.5\n    thresh = cm.max() / 2.\n    # Iterate through the results and differentiate between two text colours \n    # by using the threshold as a cut-off\n    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):\n        plt.text(j, i, format(cm[i, j], fmt),\n                 horizontalalignment = \"center\",\n                 color = \"white\" if cm[i, j] > thresh else \"black\")\n\n    plt.tight_layout()\n    plt.ylabel('True label')\n    plt.xlabel('Predicted label')\n```\n:::\n\n\n::: {.cell execution_count=44}\n``` {.python .cell-code}\n# Compute confusion matrix\nmatrix = confusion_matrix(y_test, y_mp, labels = [0,1])\nnp.set_printoptions(precision = 2)\n\n# Plot confusion matrix without normalisation\nplt.figure()\nplot_confusion_matrix(matrix, \n                      # Define classes of outcomes\n                      classes = ['Max_Phase = 0','Max_Phase = 1'], \n                      # Set normalize = True if wanting ratios instead\n                      normalize = False, \n                      title = \"Confusion matrix without normalisation\"\n                     )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nConfusion matrix, without normalization\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n[[139  63]\n [ 51 126]]\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](ML1-1_chembl_cpds_files/figure-html/cell-45-output-3.png){width=570 height=488}\n:::\n:::\n\n\nA common rule of thumb for confusion matrix was that all predicted outcomes were columns and all the true outcomes were rows. However, there might be exceptions where this was the other way round. Four different categories could be seen in the confusion matrix which were:\n\n-   True positive - Predicted Max_Phase = 1 & True Max_Phase = 1 (126 out of 189 samples)\n-   True negative - Predicted Max_Phase = 0 & True Max_Phase = 0 (139 out of 190 samples)\n-   False positive - Predicted Max_Phase = 1 & True Max_Phase = 0 (63 out of 189 samples)\n-   False negative - Predicted Max_Phase = 0 & True Max_Phase = 1 (51 out of 190 samples)\n\nBy having these four categories known would then lead us to the next section about classification report, which showed all the precision, recall, f1-score and support metrics to evaluate the performance of this classifier.\n\n<br>\n\n###### **Classification report**\n\n::: {.cell execution_count=45}\n``` {.python .cell-code}\nfrom sklearn.metrics import classification_report\nprint(classification_report(y_test, y_mp))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              precision    recall  f1-score   support\n\n           0       0.73      0.69      0.71       202\n           1       0.67      0.71      0.69       177\n\n    accuracy                           0.70       379\n   macro avg       0.70      0.70      0.70       379\nweighted avg       0.70      0.70      0.70       379\n\n```\n:::\n:::\n\n\n***Precision*** was a measure of the accuracy of a predicted outcome, where a class label had been predicted by the classifier. So in this case, we could see that for class label 1, the precision was 0.67, which corresponded to the true positive result of 126 out of 189 samples (= 0.666). It was defined by:\n\n$$\n\\text{Precision} = \\frac{\\Sigma\\ True\\ Positive}{(\\Sigma\\ True\\ Positive + \\Sigma\\ False\\ Positive)}\n$$\n\n***Recall***, also known as sensitivity (especially widely used in biostatistics and medical diagnostic fields), was a measure of the strength of the classifier to predict a positive outcome. In simple words, it measured the true positive rate. In this example, there was a total of 126 out of 177 samples (which = 0.712, for True Max_Phase = 1 row) that had a true positive outcome of having a max phase of 1. It was defined by:\n\n$$\n\\text{Recall} = \\frac{\\Sigma\\ True\\ Positive}{(\\Sigma\\ True\\ Positive + \\Sigma\\ False\\ Negative)}\n$$\n\nThe precision and recall metrics could also be calculated for class label = 0, which were shown for the row 0 in the classification report.\n\n***f1-score***, or also known as balanced F-score or F-measure, denoted the harmonic average of both precision and recall metrics. This metric would also give another indication about whether this model performed well on outcome predictions. It normally ranged from 0 (worst precision and recall) to 1 (perfect precision and recall). For this particular classifier, f1-score was at 0.69 (for class label = 1), which was definitely not at its worst, but also could be further improved. It was defined as:\n\n$$\n\\text{F1-score} = \\frac{2 \\times (Precision \\times Recall)}{(Precision + Recall)}\n$$\n\n***Support***, which some readers might have already worked out how the numbers were derived, was the total number of true samples in each class label (reading row-wise from the confusion matrix). The main purpose of showing this metric was to help clarifying whether the model or classifier had a reasonably balanced dataset for each class or otherwise.\n\n<br>\n\n###### **Log loss**\n\nLog loss could be used as another gauge to show how good the classifier was at making the outcome predictions. The further the predicted probability was from the true value, the larger the log loss, which was also ranged from 0 to 1. Ideally, the smaller the log loss the better the model would be. Here, we had a log loss of 0.607 for this particular model.\n\n::: {.cell execution_count=46}\n``` {.python .cell-code}\n# Log loss\nfrom sklearn.metrics import log_loss\nlog_loss(y_test, y_mp_proba)\n```\n\n::: {.cell-output .cell-output-display execution_count=92}\n```\n0.606602645025058\n```\n:::\n:::\n\n\n#### **Discussions and conclusion**\n\nSo here I've completed a very basic LR classifier model for ChEMBL compound dataset. By no means was this a perfect ML model as I haven't actually changed the default settings of *scikit-learn*'s LogisticRegression() classifier, with examples such as adjusting C, a regularization parameter which was set at '1.0' by default, and also solvers, which could take in different algorithms for use in optimisation problems and normally set as 'lbfgs' by default.\n\nSo with this default LR model, the evaluation metrics demonstrated a LR classifer of moderate quality to predict the approval outcomes on ChEMBL small molecules, with a lot of rooms for improvements. Therefore, I could not yet confirm fully that the physicochemical parameters chosen would be the best ones to predict the approval outcomes for any small molecules. However, I might be okay to say that these molecular parameters were on the right track to help with making this prediction.\n\nTo further improve this model, I could possibly trial changing the C value and use different solvers to see if better outcomes could be achieved, or even add more molecular parameters in the model to test. I could have also trialled adding more class labels, e.g. making it between max phase 1, 2 and 4, or a mix-and-match between each max phase category. Other things to consider would be to use other types of ML methods such as naive Bayes, K-nearest neighbours or decision trees and so on. To tackle the problem thoroughly, I would most likely need to do an ensemble of different ML models to find out which model would be the most optimal to answer our target question.\n\n<br>\n\n#### **Final words**\n\nI've experienced the fun of ML after completing this project. The idea was to build on what I knew gradually and enjoy what ML could do when making critical decisions. From what I've learnt about ML so far (and definitely more to learn) was that the quality of data was vital for making meaningful interpretations of the results.\n\nHowever, jumping back to present time, I'll need to work on my second project first, which is about using Rust interactively via Jupyter notebook. At the moment, I'm not sure how long it will take or how the content will play out. I'll certainly do as much as I can since Rust is very new to me. If I get very stuck, I'd most likely continue on this ML series. Thanks for reading.\n\n<br>\n\n#### **References**\n\nI've listed below most of the references used throughout this project. Again, huge thanks could not be forgotten for our online communities, and definitely also towards the references I've used here.\n\n-   [scikit-learn documentation](https://scikit-learn.org/stable/index.html)\n-   [Scikit-learn: Machine Learning in Python](https://jmlr.csail.mit.edu/papers/v12/pedregosa11a.html), Pedregosa *et al.*, JMLR 12, pp. 2825-2830, 2011.\n-   Bruce, P., Bruce, A. & Gedeck P. (2020). Practical statistics for data scientists. O'Reilly.\n-   [Stack Overflow](https://stackoverflow.com)\n-   Polars references:\n    1.  [Polars - User Guide](https://pola-rs.github.io/polars-book/user-guide/introduction.html) - https://pola-rs.github.io/polars-book/user-guide/introduction.html\n    2.  [Polars documentation](https://pola-rs.github.io/polars/py-polars/html/index.html#) - https://pola-rs.github.io/polars/py-polars/html/index.html#\n    3.  [Polars GitHub repository](https://github.com/pola-rs/polars) - https://github.com/pola-rs/polars\n\n",
    "supporting": [
      "ML1-1_chembl_cpds_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}