---
title: "The beginning of cheminformatics and data science journey"
author: "Jennifer HY Lin"
date: "2022-01-28"
categories: [Blog]
---

After my PhD study came to an end at around the end of 2018 to early 2019, I've decided to return to New Zealand. This was followed by my tumultuous postdoc searching story and also a solitude time for myself to dig deeper into what I would really like to do research-wise. This, of course, then led to the beginning of the COVID-19 pandemic in early 2020, which in a sense has been world-changing (I don't know what other words or terms can better describe it) and its after-effect is still hanging around until this very moment...

Regarding to the postdoc job searching, this has made me ponder really hard about what sort of research I would really like to work on. As I've spent time preparing my CV, writing different cover letters, applying for different postdoc-related roles and also after being invited to five job interviews, I've decided that it was not quite enough about what I've done so far in Masters and PhD work... I'm still lacking some skills. I've also realised that I do not necessarily like the traditional academic postdoc work (discovered while and after I've applied for numerous postdoc posts in 2019) and also I'm more inclined to work on computational chemistry and cheminformatics side of research.

Another "elephant-in-the-room" issue was that it has been very difficult to publish a first-author paper from my PhD research work, due to the impact from the development of COVID-19 pandemic for the last two years (my overseas-based collaborators have been hit hard particularly and they were still working on part of the experiments until the first quarter of the year 2021) and hence probably this was the most likely the reason that I did not get final offers in some academic postdoc positions, due to the lack of first-author papers.

Because of all the issues and problems, I've still kept my old pharmacist job as my side job while I start on a new journey in learning data science. I've tested the water since 2019 and temporarily ceased the learning in 2020 due to the pandemic (I worked full-time in hospital which was also another unforgettable experience of course). From the last quarter of 2021, I've made up my mind to go full board with data science (as I can't see my PhD research work being published any time soon so it's time to consider a possible change in direction). I thought I'd like to learn about it systematically with some sort of logical structures in the course so that I can understand a basic full picture about it in a reasonably short time (I realise data science itself is a profound field) and if there are some sort of accreditations, this would be even better. This was also the sole reason why I started on Coursera's IBM data science professional certificate in the last quarter of 2021. After learning more about it, I've realised how much it has overlapped with cheminformatics and my interests in both areas grew more and more as time goes.

I have now completed the data science professional certificate, which consisted of a total of 10 courses with assessments, assignments and portfolios (certificates and/or IBM badges viewable from my LinkedIn profile). I have managed to finish the course within about 5 months (from mid-September 2021 till end of January 2022) while working part-time as a locum pharmacist. Although it's not a perfect course, I think it reflects very nicely what the reality will be like when working as a data scientist or cheminformatician -- imperfections in data sources, data analyses and presentations that need to be corrected or problems that need to be solved by looking for answers and working on possible solutions. I think it's a useful course for newcomers who want to learn more about data science and also for the professionals who would like to refresh or reaffirm knowledge and skills (this is by no means a promotion about Coursera's data science course but just a personal learning experience only, other course providers may equally provide similar experiences and I would encourage anyone who's interested to look around and see what other courses are available).
